"""SRD 5.2 (Regeln 2024) – eigene Kurzfassungen, CC-BY-4.0-Quelle.
Völker haben 2024 keine Attributsboni mehr – die kommen aus dem Hintergrund."""
from common import F, abil, skills, ALL_SKILLS

NO_ASI = ("— (über den Hintergrund)", "— (from your background)")
DV = lambda ft=60: F(("Dunkelsicht", "Darkvision"), (f"Dunkelsicht {ft} ft.", f"Darkvision {ft} ft."))
PB = ("Übungsbonus", "proficiency bonus")

RACES = [
 dict(key="dragonborn", name=("Drachenblütiger", "Dragonborn"), size=("Mittel", "Medium"), speed=30, darkvision=60, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Nachfahren von Drachen mit Odem und – später – Flügeln.", "Descendants of dragons with breath and, later, wings."),
      traits=[F(("Drachenahnen", "Draconic Ancestry"), ("Drachenart wählen – bestimmt die Schadensart.", "Choose a dragon type – it sets your damage type."), [{"type": "damage_type", "count": 1}]),
              F(("Odemwaffe", "Breath Weapon"), ("Ersetzt einen Angriff: 15-ft-Kegel oder 30-ft-Linie, 1W10 (steigt bis 4W10), GES-Rettungswurf. Übungsbonus-mal pro langer Rast.", "Replaces an attack: 15 ft cone or 30 ft line, 1d10 (up to 4d10), DEX save. Proficiency bonus times per long rest.")),
              F(("Schadensresistenz", "Damage Resistance"), ("Resistenz gegen die Schadensart deiner Ahnen.", "Resistance to your ancestry's damage type.")), DV(),
              F(("Drakonischer Flug", "Draconic Flight"), ("Ab Stufe 5: Bonusaktion, 10 Minuten Flügel mit Fluggeschwindigkeit. Einmal pro langer Rast.", "From level 5: bonus action, spectral wings with a flying speed for 10 minutes. Once per long rest."))]),
 dict(key="dwarf", name=("Zwerg", "Dwarf"), size=("Mittel", "Medium"), speed=30, darkvision=120, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Zäh, ausdauernd und mit dem Stein verbunden.", "Tough, enduring and bound to stone."),
      traits=[DV(120), F(("Zwergische Widerstandskraft", "Dwarven Resilience"), ("Resistenz gegen Gift; Vorteil gegen Vergiftung.", "Resistance to poison; advantage against being poisoned.")),
              F(("Zwergische Zähigkeit", "Dwarven Toughness"), ("+1 Trefferpunkt-Maximum pro Stufe.", "+1 hit point maximum per level.")),
              F(("Steingespür", "Stonecunning"), ("Bonusaktion: 10 Minuten Erschütterungssinn 60 ft auf Stein. Übungsbonus-mal pro langer Rast.", "Bonus action: tremorsense 60 ft on stone for 10 minutes. Proficiency bonus times per long rest."))]),
 dict(key="elf", name=("Elf", "Elf"), size=("Mittel", "Medium"), speed=30, darkvision=60, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Magische, langlebige Wesen mit Abstammung aus Drow, Hochelfen oder Waldelfen.", "Magical, long-lived people of drow, high elf or wood elf lineage."),
      traits=[DV(), F(("Elfische Abstammung", "Elven Lineage"), ("Drow, Hochelf oder Waldelf: Zaubertrick und weitere Zauber auf Stufe 3 und 5.", "Drow, high elf or wood elf: a cantrip and more spells at levels 3 and 5.")),
              F(("Feenblut", "Fey Ancestry"), ("Vorteil gegen Bezauberung.", "Advantage against being charmed.")),
              F(("Scharfe Sinne", "Keen Senses"), ("Geübt in Einsicht, Wahrnehmung oder Überleben.", "Proficient in Insight, Perception or Survival."), [{"type": "skill", "count": 1}]),
              F(("Trance", "Trance"), ("4 Stunden Trance ersetzen eine lange Rast an Schlaf.", "4 hours of trance replace sleep for a long rest."))]),
 dict(key="gnome", name=("Gnom", "Gnome"), size=("Klein", "Small"), speed=30, darkvision=60, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Klug und erfinderisch – Wald- oder Felsengnome.", "Clever and inventive – forest or rock gnomes."),
      traits=[DV(), F(("Gnomische Gerissenheit", "Gnomish Cunning"), ("Vorteil bei INT-, WEI- und CHA-Rettungswürfen.", "Advantage on INT, WIS and CHA saving throws.")),
              F(("Gnomische Abstammung", "Gnomish Lineage"), ("Waldgnom (Kleine Illusion, mit Tieren sprechen) oder Felsengnom (Ausbessern, Taschenspielerei, Uhrwerkspielzeug).", "Forest gnome (minor illusion, speak with animals) or rock gnome (mending, prestidigitation, clockwork toys)."))]),
 dict(key="goliath", name=("Goliath", "Goliath"), size=("Mittel", "Medium"), speed=35, darkvision=0, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Riesenblut in den Adern – groß, stark und unerschrocken.", "Giant blood in their veins – tall, strong and fearless."),
      traits=[F(("Riesenahnen", "Giant Ancestry"), ("Eine Gabe wählen: Wolkensprung, Feuerbrand, Frostkälte, Hügelsturz, Steinausdauer oder Sturmdonner. Übungsbonus-mal pro langer Rast.", "Choose a boon: Cloud's Jaunt, Fire's Burn, Frost's Chill, Hill's Tumble, Stone's Endurance or Storm's Thunder. Proficiency bonus times per long rest.")),
              F(("Große Gestalt", "Large Form"), ("Ab Stufe 5: Bonusaktion, 10 Minuten groß – Vorteil auf STR-Proben, +10 ft. Einmal pro langer Rast.", "From level 5: bonus action, Large for 10 minutes – advantage on STR checks, +10 ft. Once per long rest.")),
              F(("Kräftiger Körperbau", "Powerful Build"), ("Vorteil gegen Ende des Gepacktseins; trägt wie eine Größenkategorie größer.", "Advantage to end being grappled; carry as one size larger."))]),
 dict(key="halfling", name=("Halbling", "Halfling"), size=("Klein", "Small"), speed=30, darkvision=0, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Klein, mutig und vom Glück begünstigt.", "Small, brave and favoured by luck."),
      traits=[F(("Tapfer", "Brave"), ("Vorteil gegen Verängstigung.", "Advantage against being frightened.")),
              F(("Halblings-Gewandtheit", "Halfling Nimbleness"), ("Durch den Raum größerer Kreaturen bewegen.", "Move through the space of larger creatures.")),
              F(("Glück", "Luck"), ("Eine gewürfelte 1 beim W20 neu würfeln.", "Reroll a 1 on a d20 test.")),
              F(("Natürlich verstohlen", "Naturally Stealthy"), ("Verstecken hinter größeren Kreaturen möglich.", "Hide behind larger creatures."))]),
 dict(key="human", name=("Mensch", "Human"), size=("Mittel oder klein", "Medium or small"), speed=30, darkvision=0, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Anpassungsfähig, ehrgeizig und einfallsreich.", "Adaptable, ambitious and resourceful."),
      traits=[F(("Einfallsreich", "Resourceful"), ("Nach jeder langen Rast Heldenhafte Inspiration.", "Gain Heroic Inspiration after each long rest.")),
              F(("Geschickt", "Skillful"), ("Geübt in einer Fertigkeit deiner Wahl.", "Proficient in one skill of your choice."), [{"type": "skill", "count": 1}]),
              F(("Vielseitig", "Versatile"), ("Ein Herkunftstalent deiner Wahl.", "One origin feat of your choice."), [{"type": "feat", "count": 1}])]),
 dict(key="orc", name=("Ork", "Orc"), size=("Mittel", "Medium"), speed=30, darkvision=120, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Ausdauernd und von unbändiger Kraft.", "Enduring and of untamed strength."),
      traits=[F(("Adrenalinschub", "Adrenaline Rush"), ("Spurt als Bonusaktion und temporäre TP in Höhe des Übungsbonus. Übungsbonus-mal pro Rast.", "Dash as a bonus action and gain temporary HP equal to your proficiency bonus. Proficiency bonus times per rest.")),
              DV(120), F(("Unermüdliche Ausdauer", "Relentless Endurance"), ("Fällst du auf 0 TP, bleibst du bei 1 TP. Einmal pro langer Rast.", "When reduced to 0 HP you drop to 1 instead. Once per long rest."))]),
 dict(key="tiefling", name=("Tiefling", "Tiefling"), size=("Mittel oder klein", "Medium or small"), speed=30, darkvision=60, asi=NO_ASI,
      languages=("Gemeinsprache + 2 Sprachen", "Common + 2 languages"), desc=("Mit dem Erbe der unteren Ebenen – abyssisch, chthonisch oder infernalisch.", "Heirs of the lower planes – abyssal, chthonic or infernal."),
      traits=[DV(), F(("Unholdisches Erbe", "Fiendish Legacy"), ("Abyssisch, chthonisch oder infernalisch: Resistenz, Zaubertrick und Zauber auf Stufe 3 und 5.", "Abyssal, chthonic or infernal: a resistance, a cantrip and spells at levels 3 and 5.")),
              F(("Andersweltliche Präsenz", "Otherworldly Presence"), ("Zaubertrick Thaumaturgie.", "Thaumaturgy cantrip."))]),
]

BACKGROUNDS = [
 dict(key="acolyte", name=("Akolyth", "Acolyte"), abilities=("INT, WEI, CHA", "INT, WIS, CHA"), skills=skills("insight", "religion"), languages=("—", "—"),
      tools=("Kalligrafie-Ausrüstung", "Calligrapher's supplies"), equipment=("Kalligrafie-Ausrüstung, Buch, heiliges Symbol, Pergament, Gewänder, 8 GM – oder 50 GM", "Calligrapher's supplies, book, holy symbol, parchment, robe, 8 gp – or 50 gp"),
      feature=("Herkunftstalent: Magie-Eingeweihter (Kleriker).", "Origin feat: Magic Initiate (Cleric)."), desc=("Dienst in einem Tempel hat dich geprägt.", "Service in a temple has shaped you.")),
 dict(key="criminal", name=("Krimineller", "Criminal"), abilities=("GES, KON, INT", "DEX, CON, INT"), skills=skills("sleight", "stealth"), languages=("—", "—"),
      tools=("Diebeswerkzeug", "Thieves' tools"), equipment=("2 Dolche, Diebeswerkzeug, Brecheisen, 2 Beutel, Reisekleidung, 16 GM – oder 50 GM", "2 daggers, thieves' tools, crowbar, 2 pouches, traveler's clothes, 16 gp – or 50 gp"),
      feature=("Herkunftstalent: Wachsam.", "Origin feat: Alert."), desc=("Du hast dich in dunklen Gassen durchgeschlagen.", "You made your way in dark alleys.")),
 dict(key="sage", name=("Weiser", "Sage"), abilities=("KON, INT, WEI", "CON, INT, WIS"), skills=skills("arcana", "history"), languages=("—", "—"),
      tools=("Kalligrafie-Ausrüstung", "Calligrapher's supplies"), equipment=("Kampfstab, Kalligrafie-Ausrüstung, Buch, Pergament, Gewand, 8 GM – oder 50 GM", "Quarterstaff, calligrapher's supplies, book, parchment, robe, 8 gp – or 50 gp"),
      feature=("Herkunftstalent: Magie-Eingeweihter (Magier).", "Origin feat: Magic Initiate (Wizard)."), desc=("Jahre zwischen Büchern und Gelehrten.", "Years among books and scholars.")),
 dict(key="soldier", name=("Soldat", "Soldier"), abilities=("STR, GES, KON", "STR, DEX, CON"), skills=skills("athletics", "intimidation"), languages=("—", "—"),
      tools=("Ein Spielset", "One gaming set"), equipment=("Speer, Kurzbogen, 20 Pfeile, Spielset, Heilerausrüstung, Köcher, Reisekleidung, 14 GM – oder 50 GM", "Spear, shortbow, 20 arrows, gaming set, healer's kit, quiver, traveler's clothes, 14 gp – or 50 gp"),
      feature=("Herkunftstalent: Wilder Angreifer.", "Origin feat: Savage Attacker."), desc=("Du hast für eine Armee oder Miliz gekämpft.", "You fought for an army or militia.")),
]

def FT(key, de, en, cat, prereq, desc, ben): return dict(key=key, name=(de, en), cat=cat, prereq=prereq, desc=desc, benefits=ben)
ORI, GEN, FST, EPI = ("Herkunft", "Origin"), ("Allgemein", "General"), ("Kampfstil", "Fighting Style"), ("Epische Gabe", "Epic Boon")
L4, L19 = ("Stufe 4+", "Level 4+"), ("Stufe 19+", "Level 19+")
FEATS = [
 FT("alert", "Wachsam", "Alert", ORI, ("—", "—"), ("Immer bereit.", "Always ready."), ("Übungsbonus auf Initiative; Initiative mit einem Verbündeten tauschen.", "Add proficiency bonus to initiative; swap initiative with an ally.")),
 FT("magic_initiate", "Magie-Eingeweihter", "Magic Initiate", ORI, ("—", "—"), ("Ein Hauch von Magie.", "A touch of magic."), ("Zwei Zaubertricks und ein Zauber 1. Grades aus der Kleriker-, Druiden- oder Magierliste.", "Two cantrips and one 1st-level spell from the cleric, druid or wizard list.")),
 FT("savage_attacker", "Wilder Angreifer", "Savage Attacker", ORI, ("—", "—"), ("Wuchtige Treffer.", "Brutal hits."), ("Einmal pro Zug Waffenschaden zweimal würfeln, den besseren nehmen.", "Once per turn roll weapon damage twice and use either.")),
 FT("skilled", "Begabt", "Skilled", ORI, ("—", "—"), ("Vielseitig ausgebildet.", "Broadly trained."), ("Geübt in drei Fertigkeiten oder Werkzeugen.", "Proficiency in three skills or tools.")),
 FT("asi", "Attributswerterhöhung", "Ability Score Improvement", GEN, (L4[0], L4[1]), ("Stärker, klüger, schneller.", "Stronger, smarter, faster."), ("Ein Attribut +2 oder zwei Attribute +1 (höchstens 20).", "One ability +2 or two abilities +1 (max 20).")),
 FT("grappler", "Ringer", "Grappler", GEN, ("Stufe 4+, STR oder GES 13", "Level 4+, STR or DEX 13"), ("Meister des Haltegriffs.", "Master of holds."), ("+1 STR oder GES; Schlag und Packen in einem; Vorteil gegen Gepackte; Gepackte ohne Verlangsamung bewegen.", "+1 STR or DEX; punch and grab together; advantage against grappled targets; move them without slowing.")),
 FT("archery", "Bogenschießen", "Archery", FST, ("Kampfstil-Merkmal", "Fighting Style feature"), ("Präzise auf Distanz.", "Precise at range."), ("+2 auf Angriffe mit Fernkampfwaffen.", "+2 to attack rolls with ranged weapons.")),
 FT("defense", "Verteidigung", "Defense", FST, ("Kampfstil-Merkmal", "Fighting Style feature"), ("Schwer zu treffen.", "Hard to hit."), ("+1 RK in leichter, mittlerer oder schwerer Rüstung.", "+1 AC while wearing light, medium or heavy armour.")),
 FT("great_weapon", "Kampf mit großen Waffen", "Great Weapon Fighting", FST, ("Kampfstil-Merkmal", "Fighting Style feature"), ("Mit beiden Händen.", "With both hands."), ("Beim Schaden mit Zweihand- oder vielseitigen Waffen zählen 1 und 2 als 3.", "With two-handed or versatile weapons, treat damage rolls of 1 or 2 as 3.")),
 FT("two_weapon", "Kampf mit zwei Waffen", "Two-Weapon Fighting", FST, ("Kampfstil-Merkmal", "Fighting Style feature"), ("Zwei Klingen, ein Rhythmus.", "Two blades, one rhythm."), ("Attributsmodifikator auch auf den Schaden des Zusatzangriffs.", "Add your ability modifier to the extra attack's damage.")),
 FT("boon_combat", "Gabe der Kampfkraft", "Boon of Combat Prowess", EPI, (L19[0], L19[1]), ("Unaufhaltsam.", "Unstoppable."), ("+1 Attribut; einmal pro Zug einen verfehlten Angriff in einen Treffer verwandeln.", "+1 ability; once per turn turn a miss into a hit.")),
 FT("boon_travel", "Gabe der Dimensionsreise", "Boon of Dimensional Travel", EPI, (L19[0], L19[1]), ("Zwischen den Orten.", "Between places."), ("+1 Attribut; nach Angriff oder Zauber 30 ft teleportieren.", "+1 ability; teleport 30 ft after an attack or spell.")),
 FT("boon_fate", "Gabe des Schicksals", "Boon of Fate", EPI, (L19[0], L19[1]), ("Das Schicksal biegen.", "Bend fate."), ("+1 Attribut; 2W4 zu einem W20-Wurf addieren oder abziehen (einmal pro Rast).", "+1 ability; add or subtract 2d4 to a d20 test (once per rest).")),
 FT("boon_offense", "Gabe des unwiderstehlichen Angriffs", "Boon of Irresistible Offense", EPI, (L19[0], L19[1]), ("Nichts hält stand.", "Nothing withstands."), ("+1 STR oder GES; Hieb-, Stich- und Wuchtschaden ignoriert Resistenz; Extraschaden bei einer 20.", "+1 STR or DEX; your weapon damage ignores resistance; extra damage on a 20.")),
 FT("boon_recall", "Gabe der Zaubererinnerung", "Boon of Spell Recall", EPI, (L19[0], L19[1]), ("Magie ohne Ende.", "Endless magic."), ("+1 INT, WEI oder CHA; einen Zauber 1.–4. Grades ohne Zauberplatz wirken (einmal pro langer Rast).", "+1 INT, WIS or CHA; cast a 1st–4th level spell without a slot (once per long rest).")),
 FT("boon_night", "Gabe des Nachtgeistes", "Boon of the Night Spirit", EPI, (L19[0], L19[1]), ("Eins mit den Schatten.", "One with shadows."), ("+1 Attribut; im Dämmerlicht unsichtbar werden; Resistenz in Schatten.", "+1 ability; become invisible in dim light; resistance while in shadows.")),
 FT("boon_truesight", "Gabe des wahren Blicks", "Boon of Truesight", EPI, (L19[0], L19[1]), ("Nichts bleibt verborgen.", "Nothing stays hidden."), ("+1 Attribut; Wahrsicht 60 ft.", "+1 ability; truesight 60 ft.")),
]

# ── Klassen (2024) ──────────────────────────────────────────────────────────
from common import ASI
EPIC = F(("Epische Gabe", "Epic Boon"), ("Ein Talent der Kategorie „Epische Gabe“ (oder ein anderes passendes).", "An Epic Boon feat (or another feat you qualify for)."), [{"type": "feat", "count": 1}])
WM = lambda n: F(("Waffenmeisterschaft", "Weapon Mastery"), (f"Meisterschafts-Eigenschaften von {n} Waffenarten nutzen (wechselbar nach langer Rast).", f"Use the mastery properties of {n} kinds of weapons (swap after a long rest)."))
FS = F(("Kampfstil", "Fighting Style"), ("Ein Talent der Kategorie Kampfstil.", "A Fighting Style feat."), [{"type": "fighting_style", "count": 1}])
EXTRA = F(("Zusätzlicher Angriff", "Extra Attack"), ("Mit der Angriffsaktion zweimal angreifen.", "Attack twice when you take the Attack action."))
SPELLS = lambda a: F(("Zauberwirken", "Spellcasting"), (f"Zauber aus der Klassenliste vorbereiten und wirken. Attribut: {a[0]}.", f"Prepare and cast spells from your class list. Ability: {a[1]}."))
SUB = lambda de, en: F((de, en), ("Wähle deine Unterklasse.", "Choose your subclass."), [{"type": "subclass", "count": 1}])
SC = F(("Merkmal der Unterklasse", "Subclass feature"), ("Merkmal deiner gewählten Unterklasse.", "Feature from your chosen subclass."))

def lv(d, asi=(4, 8, 12, 16)):
    out = {k: list(v) for k, v in d.items()}
    for l in asi: out.setdefault(l, []).append(ASI)
    out.setdefault(19, []).append(EPIC)
    return out

CLASSES = [
 dict(key="barbarian", name=("Barbar", "Barbarian"), hd="d12", primary="str", caster=False, saves=abil("str", "con"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("animal", "athletics", "intimidation", "nature", "perception", "survival"),
      desc=("Ein Krieger urtümlicher Wut.", "A warrior of primal rage."),
      features=lv({1: [F(("Kampfrausch", "Rage"), ("Bonusaktion: Resistenz gegen Hieb-, Stich- und Wuchtschaden, Bonusschaden, Vorteil auf STR-Proben. Eine Nutzung kehrt nach kurzer Rast zurück.", "Bonus action: resistance to bludgeoning, piercing and slashing, bonus damage, advantage on STR checks. One use returns on a short rest.")),
                       F(("Ungerüstete Verteidigung", "Unarmored Defense"), ("Ohne Rüstung: RK 10 + GES + KON.", "Without armour: AC 10 + DEX + CON.")), WM(2)],
                   2: [F(("Gefahrensinn", "Danger Sense"), ("Vorteil bei GES-Rettungswürfen.", "Advantage on DEX saving throws.")),
                       F(("Rücksichtsloser Angriff", "Reckless Attack"), ("Vorteil auf STR-Angriffe – Angriffe gegen dich ebenfalls mit Vorteil.", "Advantage on STR attacks – attacks against you also have advantage."))],
                   3: [SUB("Barbaren-Unterklasse", "Barbarian Subclass"), F(("Urwissen", "Primal Knowledge"), ("Eine weitere Fertigkeit; im Kampfrausch einige Proben mit STR.", "One more skill; while raging use STR for some checks."))],
                   5: [EXTRA, F(("Schnelle Bewegung", "Fast Movement"), ("+10 ft Geschwindigkeit ohne schwere Rüstung.", "+10 ft speed without heavy armour."))], 6: [SC],
                   7: [F(("Wilder Instinkt", "Feral Instinct"), ("Vorteil auf Initiative.", "Advantage on initiative.")), F(("Instinktiver Ansprung", "Instinctive Pounce"), ("Beim Aktivieren des Kampfrauschs halbe Geschwindigkeit bewegen.", "Move half your speed when you enter a rage."))],
                   9: [F(("Brutaler Schlag", "Brutal Strike"), ("Auf Vorteil verzichten: +1W10 Schaden und ein Zusatzeffekt (Stoß oder Verlangsamung).", "Forgo advantage: +1d10 damage and an extra effect (push or hamstring)."))], 10: [SC],
                   11: [F(("Unerbittlicher Kampfrausch", "Relentless Rage"), ("Auf 0 TP im Kampfrausch: KON-Rettungswurf, bei Erfolg TP = doppelte Stufe.", "At 0 HP while raging: CON save, on success HP equal to twice your level."))],
                   13: [F(("Verbesserter brutaler Schlag", "Improved Brutal Strike"), ("Weitere Effekte für Brutaler Schlag.", "More Brutal Strike effects."))], 14: [SC],
                   15: [F(("Anhaltender Kampfrausch", "Persistent Rage"), ("Kampfrausch hält 10 Minuten; bei Initiative Nutzungen zurück.", "Rage lasts 10 minutes; regain uses when rolling initiative."))],
                   17: [F(("Verbesserter brutaler Schlag", "Improved Brutal Strike"), ("+2W10 und zwei Effekte.", "+2d10 and two effects."))],
                   18: [F(("Unbezwingbare Kraft", "Indomitable Might"), ("STR-Proben mindestens in Höhe des STR-Werts.", "STR checks at least equal to your STR score."))],
                   20: [F(("Urgewaltiger Champion", "Primal Champion"), ("+4 STR und +4 KON, Höchstwert 25.", "+4 STR and +4 CON, maximum 25."))]})),
 dict(key="bard", name=("Barde", "Bard"), hd="d8", primary="cha", caster=True, saves=abil("dex", "cha"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen", "Simple weapons"), tools=("Drei Musikinstrumente", "Three musical instruments"),
      skill_count=3, skill_options=skills(*ALL_SKILLS), desc=("Ein Magier der Musik und Worte.", "A mage of music and words."),
      features=lv({1: [F(("Bardische Inspiration", "Bardic Inspiration"), ("Bonusaktion: Verbündeter erhält W6 für einen W20-Wurf (steigt bis W12). CHA-mal pro langer Rast.", "Bonus action: an ally gains a d6 for a d20 test (up to d12). CHA times per long rest.")), SPELLS(("CHA", "CHA"))],
                   2: [F(("Expertise", "Expertise"), ("Doppelter Übungsbonus in zwei Fertigkeiten (Stufe 9: zwei weitere).", "Double proficiency in two skills (two more at level 9)."), [{"type": "skill", "count": 2}]),
                       F(("Alleskönner", "Jack of All Trades"), ("Halber Übungsbonus auf ungeübte Proben.", "Half proficiency on unproficient checks."))],
                   3: [SUB("Barden-Unterklasse", "Bard Subclass")], 5: [F(("Quell der Inspiration", "Font of Inspiration"), ("Inspiration auch nach kurzer Rast; Zauberplatz gegen Inspiration tauschen.", "Inspiration returns on a short rest; trade a spell slot for a use."))],
                   6: [SC], 7: [F(("Gegenzauber-Lied", "Countercharm"), ("Reaktion: misslungenen Rettungswurf gegen Bezauberung/Verängstigung wiederholen lassen.", "Reaction: let a creature reroll a failed save against charm or fear."))],
                   10: [F(("Magische Geheimnisse", "Magical Secrets"), ("Zauber aus Barden-, Kleriker-, Druiden- und Magierliste vorbereiten.", "Prepare spells from the bard, cleric, druid and wizard lists."))], 14: [SC],
                   18: [F(("Überlegene Inspiration", "Superior Inspiration"), ("Bei Initiative Inspiration bis auf 2 auffüllen.", "Regain inspiration up to 2 when rolling initiative."))],
                   20: [F(("Worte der Schöpfung", "Words of Creation"), ("Machtwort heilen und Machtwort töten immer vorbereitet; mit zwei Zielen wirkbar.", "Power word heal and power word kill always prepared; can target two creatures."))]})),
 dict(key="cleric", name=("Kleriker", "Cleric"), hd="d8", primary="wis", caster=True, saves=abil("wis", "cha"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("history", "insight", "medicine", "persuasion", "religion"), desc=("Ein Werkzeug göttlicher Macht.", "An instrument of divine power."),
      features=lv({1: [SPELLS(("WEI", "WIS")), F(("Göttliche Ordnung", "Divine Order"), ("Beschützer (schwere Rüstung, Kriegswaffen) oder Thaumaturg (Zaubertrick, Arkana/Religion).", "Protector (heavy armour, martial weapons) or Thaumaturge (cantrip, Arcana/Religion)."))],
                   2: [F(("Göttliche Macht", "Channel Divinity"), ("Göttlicher Funke (heilen oder Schaden) oder Untote vertreiben; Nutzungen pro Rast.", "Divine Spark (heal or harm) or Turn Undead; uses per rest."))],
                   3: [SUB("Kleriker-Unterklasse", "Cleric Subclass")], 5: [F(("Untote versengen", "Sear Undead"), ("Vertriebene Untote erleiden gleißenden Schaden.", "Turned undead take radiant damage."))], 6: [SC],
                   7: [F(("Gesegnete Schläge", "Blessed Strikes"), ("Göttlicher Schlag (+1W8) oder wirksames Zauberwirken (+WEI auf Zaubertricks).", "Divine Strike (+1d8) or Potent Spellcasting (+WIS to cantrips)."))],
                   10: [F(("Göttliches Eingreifen", "Divine Intervention"), ("Einen Zauber bis 5. Grad ohne Platz wirken (einmal pro langer Rast).", "Cast a spell up to 5th level without a slot (once per long rest)."))],
                   14: [F(("Verbesserte gesegnete Schläge", "Improved Blessed Strikes"), ("Stärkere Wirkung der gesegneten Schläge.", "Stronger Blessed Strikes."))], 17: [SC],
                   20: [F(("Größeres göttliches Eingreifen", "Greater Divine Intervention"), ("Göttliches Eingreifen kann Wunsch wirken.", "Divine Intervention can cast wish."))]})),
 dict(key="druid", name=("Druide", "Druid"), hd="d8", primary="wis", caster=True, saves=abil("int", "wis"),
      armor=("Leichte Rüstung, Schilde", "Light armour, shields"), weapons=("Einfache Waffen", "Simple weapons"), tools=("Kräuterkunde-Ausrüstung", "Herbalism kit"),
      skill_count=2, skill_options=skills("arcana", "animal", "insight", "medicine", "nature", "perception", "religion", "survival"), desc=("Ein Priester der alten Mächte der Natur.", "A priest of the old powers of nature."),
      features=lv({1: [SPELLS(("WEI", "WIS")), F(("Druidisch", "Druidic"), ("Geheimsprache; Mit Tieren sprechen immer vorbereitet.", "Secret language; speak with animals always prepared.")),
                       F(("Urtümliche Ordnung", "Primal Order"), ("Magier (Zaubertrick, Naturkunde) oder Hüter (mittlere Rüstung, Kriegswaffen).", "Magician (cantrip, Nature) or Warden (medium armour, martial weapons)."))],
                   2: [F(("Tiergestalt", "Wild Shape"), ("Bonusaktion: in ein bekanntes Tier verwandeln; Nutzungen pro Rast.", "Bonus action: turn into a known beast; uses per rest.")),
                       F(("Wilder Gefährte", "Wild Companion"), ("Tiergestalt nutzen, um Vertrauten finden zu wirken.", "Use Wild Shape to cast find familiar."))],
                   3: [SUB("Druiden-Unterklasse", "Druid Subclass")], 5: [F(("Wildes Wiederaufleben", "Wild Resurgence"), ("Zauberplatz und Tiergestalt gegeneinander tauschen.", "Trade spell slots and Wild Shape uses."))], 6: [SC],
                   7: [F(("Elementarer Zorn", "Elemental Fury"), ("Wirksames Zauberwirken oder Urtümlicher Schlag (+1W8 Elementarschaden).", "Potent Spellcasting or Primal Strike (+1d8 elemental damage)."))], 10: [SC], 14: [SC],
                   15: [F(("Verbesserter elementarer Zorn", "Improved Elemental Fury"), ("Stärkere Wirkung des elementaren Zorns.", "Stronger Elemental Fury."))],
                   18: [F(("Tierzauber", "Beast Spells"), ("Zauber auch in Tiergestalt.", "Cast spells in Wild Shape."))],
                   20: [F(("Erzdruide", "Archdruid"), ("Tiergestalt bei Initiative zurück; Tiergestalt in Zauberplätze umwandeln; langsames Altern.", "Regain Wild Shape on initiative; convert it into spell slots; slow ageing."))]})),
 dict(key="fighter", name=("Kämpfer", "Fighter"), hd="d10", primary="str", caster=False, saves=abil("str", "con"),
      armor=("Alle Rüstungen, Schilde", "All armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("acrobatics", "animal", "athletics", "history", "insight", "intimidation", "persuasion", "perception", "survival"), desc=("Meister aller Waffen und Rüstungen.", "A master of all weapons and armour."),
      features=lv({1: [FS, F(("Durchatmen", "Second Wind"), ("Bonusaktion: 1W10 + Stufe TP heilen; mehrere Nutzungen pro Rast.", "Bonus action: heal 1d10 + level HP; several uses per rest.")), WM(3)],
                   2: [F(("Tatendrang", "Action Surge"), ("Eine zusätzliche Aktion (ab Stufe 17 zweimal pro Rast).", "One extra action (twice per rest from level 17).")),
                       F(("Taktischer Verstand", "Tactical Mind"), ("Durchatmen nutzen, um eine misslungene Probe um 1W10 zu verbessern.", "Spend Second Wind to add 1d10 to a failed ability check."))],
                   3: [SUB("Kämpfer-Unterklasse", "Fighter Subclass")],
                   5: [EXTRA, F(("Taktischer Wechsel", "Tactical Shift"), ("Beim Durchatmen halbe Bewegung ohne Gelegenheitsangriffe.", "When you use Second Wind, move half speed without provoking."))],
                   6: [ASI], 7: [SC],
                   9: [F(("Unbeugsam", "Indomitable"), ("Rettungswurf wiederholen, + Stufe (Stufe 13/17: weitere Nutzungen).", "Reroll a save adding your level (more uses at 13/17).")),
                       F(("Taktischer Meister", "Tactical Master"), ("Meisterschaft bei Angriffen durch Stoßen, Verlangsamen oder Schwächen ersetzen.", "Replace a weapon's mastery with Push, Sap or Slow."))], 10: [SC],
                   11: [F(("Zwei zusätzliche Angriffe", "Two Extra Attacks"), ("Dreimal angreifen.", "Attack three times."))],
                   13: [F(("Gezielte Angriffe", "Studied Attacks"), ("Nach einem Fehlschlag Vorteil gegen dasselbe Ziel.", "After a miss, advantage on your next attack against that target."))], 14: [ASI], 15: [SC], 18: [SC],
                   20: [F(("Drei zusätzliche Angriffe", "Three Extra Attacks"), ("Viermal angreifen.", "Attack four times."))]})),
 dict(key="monk", name=("Mönch", "Monk"), hd="d8", primary="dex", caster=False, saves=abil("str", "dex"),
      armor=("Keine", "None"), weapons=("Einfache Waffen, leichte Kriegswaffen", "Simple weapons, light martial weapons"), tools=("Ein Handwerkszeug oder Instrument", "One artisan's tool or instrument"),
      skill_count=2, skill_options=skills("acrobatics", "athletics", "history", "insight", "religion", "stealth"), desc=("Kampfkünstler, der seine innere Kraft bündelt.", "A martial artist channelling inner power."),
      features=lv({1: [F(("Kampfkunst", "Martial Arts"), ("Kampfkunstwürfel (W6, steigt); waffenloser Bonusangriff; GES für Mönchswaffen.", "Martial arts die (d6, scales); bonus unarmed strike; DEX for monk weapons.")),
                       F(("Ungerüstete Verteidigung", "Unarmored Defense"), ("RK 10 + GES + WEI ohne Rüstung und Schild.", "AC 10 + DEX + WIS without armour or shield."))],
                   2: [F(("Mönchsfokus", "Monk's Focus"), ("Fokuspunkte = Stufe: Schlaghagel, Geduldige Verteidigung, Schritt des Windes.", "Focus points equal to level: Flurry of Blows, Patient Defense, Step of the Wind.")),
                       F(("Ungerüstete Bewegung", "Unarmored Movement"), ("+10 ft Geschwindigkeit (steigt).", "+10 ft speed (increases).")),
                       F(("Unheimlicher Stoffwechsel", "Uncanny Metabolism"), ("Bei Initiative Fokus auffüllen und heilen (einmal pro langer Rast).", "On initiative regain focus and heal (once per long rest)."))],
                   3: [F(("Angriffe ablenken", "Deflect Attacks"), ("Reaktion: Schaden verringern, evtl. zurückschleudern.", "Reaction: reduce damage and possibly redirect it.")), SUB("Mönchs-Unterklasse", "Monk Subclass")],
                   4: [F(("Langsamer Fall", "Slow Fall"), ("Reaktion: Fallschaden um 5 × Stufe verringern.", "Reaction: reduce falling damage by 5 × level."))],
                   5: [EXTRA, F(("Betäubender Schlag", "Stunning Strike"), ("1 Fokus: KON-Rettungswurf oder betäubt.", "1 focus: CON save or stunned."))],
                   6: [F(("Verstärkte Schläge", "Empowered Strikes"), ("Waffenloser Schaden als Energieschaden.", "Unarmed damage can be force damage.")), SC],
                   7: [F(("Entrinnen", "Evasion"), ("GES-Rettungswürfe für halben Schaden: Erfolg = kein Schaden.", "DEX saves for half damage: success = no damage."))],
                   9: [F(("Akrobatische Bewegung", "Acrobatic Movement"), ("Über Wände und Flüssigkeiten laufen.", "Run on walls and liquids."))],
                   10: [F(("Gesteigerter Fokus", "Heightened Focus"), ("Stärkere Fokus-Fähigkeiten.", "Stronger focus options.")), F(("Selbstheilung", "Self-Restoration"), ("Bezaubert, verängstigt oder vergiftet am Zugende beenden.", "End charmed, frightened or poisoned at the end of your turn."))], 11: [SC],
                   13: [F(("Energie ablenken", "Deflect Energy"), ("Angriffe ablenken gegen jede Schadensart.", "Deflect Attacks works against any damage type."))],
                   14: [F(("Disziplinierter Überlebender", "Disciplined Survivor"), ("Geübt in allen Rettungswürfen; 1 Fokus für Wiederholung.", "Proficient in all saves; 1 focus to reroll."))],
                   15: [F(("Perfekter Fokus", "Perfect Focus"), ("Bei Initiative mit wenig Fokus auf 4 auffüllen.", "With little focus left, regain up to 4 on initiative."))], 17: [SC],
                   18: [F(("Überlegene Verteidigung", "Superior Defense"), ("3 Fokus: 1 Minute Resistenz gegen fast allen Schaden.", "3 focus: 1 minute of resistance to almost all damage."))],
                   20: [F(("Körper und Geist", "Body and Mind"), ("+4 GES und +4 WEI, Höchstwert 25.", "+4 DEX and +4 WIS, maximum 25."))]})),
 dict(key="paladin", name=("Paladin", "Paladin"), hd="d10", primary="str", caster=True, saves=abil("wis", "cha"),
      armor=("Alle Rüstungen, Schilde", "All armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("athletics", "insight", "intimidation", "medicine", "persuasion", "religion"), desc=("Ein Krieger, gebunden an einen heiligen Eid.", "A warrior bound by a sacred oath."),
      features=lv({1: [F(("Handauflegen", "Lay On Hands"), ("Heilungspool von 5 × Stufe TP; auch Gift heilen.", "Healing pool of 5 × level HP; can also cure poison.")), SPELLS(("CHA", "CHA")), WM(2)],
                   2: [FS, F(("Paladin-Niederstrecken", "Paladin's Smite"), ("Göttliches Niederstrecken immer vorbereitet; einmal pro langer Rast ohne Platz.", "Divine Smite always prepared; once per long rest without a slot."))],
                   3: [F(("Göttliche Macht", "Channel Divinity"), ("Göttlicher Sinn und Fähigkeiten des Eids; Nutzungen pro Rast.", "Divine Sense and oath options; uses per rest.")), SUB("Paladin-Unterklasse", "Paladin Subclass")],
                   5: [EXTRA, F(("Treues Ross", "Faithful Steed"), ("Ross herbeirufen immer vorbereitet; einmal pro langer Rast ohne Platz.", "Find steed always prepared; once per long rest without a slot."))],
                   6: [F(("Aura des Schutzes", "Aura of Protection"), ("Du und Verbündete in 10 ft: +CHA auf Rettungswürfe.", "You and allies within 10 ft: +CHA to saving throws."))], 7: [SC],
                   9: [F(("Feinde verbannen", "Abjure Foes"), ("Göttliche Macht: Feinde verängstigen.", "Channel Divinity: frighten foes."))],
                   10: [F(("Aura des Mutes", "Aura of Courage"), ("Du und Verbündete in der Aura: immun gegen Verängstigung.", "You and allies in your aura can't be frightened."))],
                   11: [F(("Gleißende Schläge", "Radiant Strikes"), ("Waffentreffer +1W8 gleißender Schaden.", "Weapon hits deal +1d8 radiant damage."))],
                   14: [F(("Wiederherstellende Berührung", "Restoring Touch"), ("Handauflegen beendet auch Zustände.", "Lay On Hands also removes conditions."))], 15: [SC],
                   18: [F(("Aura-Erweiterung", "Aura Expansion"), ("Deine Aura reicht 30 ft.", "Your aura extends to 30 ft."))], 20: [SC]})),
 dict(key="ranger", name=("Waldläufer", "Ranger"), hd="d10", primary="dex", caster=True, saves=abil("str", "dex"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=3, skill_options=skills("animal", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"), desc=("Ein Wanderer der Wildnis mit Naturmagie.", "A wanderer of the wilds with nature magic."),
      features=lv({1: [SPELLS(("WEI", "WIS")), F(("Bevorzugter Feind", "Favored Enemy"), ("Mal des Jägers immer vorbereitet und mehrmals ohne Platz.", "Hunter's mark always prepared and free several times.")), WM(2)],
                   2: [F(("Geschickter Entdecker", "Deft Explorer"), ("Expertise in einer Fertigkeit und zwei Sprachen.", "Expertise in one skill and two languages.")), FS],
                   3: [SUB("Waldläufer-Unterklasse", "Ranger Subclass")], 5: [EXTRA],
                   6: [F(("Umherstreifen", "Roving"), ("+10 ft Geschwindigkeit, Klettern und Schwimmen.", "+10 ft speed, climb and swim speeds."))], 7: [SC],
                   9: [F(("Expertise", "Expertise"), ("Doppelter Übungsbonus in zwei Fertigkeiten.", "Double proficiency in two skills."), [{"type": "skill", "count": 2}])],
                   10: [F(("Unermüdlich", "Tireless"), ("Temporäre TP als Aktion; Erschöpfung nach kurzer Rast verringern.", "Temporary HP as an action; reduce exhaustion on a short rest."))], 11: [SC],
                   13: [F(("Gnadenloser Jäger", "Relentless Hunter"), ("Schaden bricht die Konzentration auf Mal des Jägers nicht.", "Damage can't break concentration on hunter's mark."))],
                   14: [F(("Schleier der Natur", "Nature's Veil"), ("Bonusaktion: bis zum nächsten Zug unsichtbar.", "Bonus action: invisible until your next turn."))], 15: [SC],
                   17: [F(("Präziser Jäger", "Precise Hunter"), ("Vorteil gegen das Ziel deines Mals.", "Advantage against the target of your mark."))],
                   18: [F(("Wilde Sinne", "Feral Senses"), ("Blindsicht 30 ft.", "Blindsight 30 ft."))],
                   20: [F(("Feindbezwinger", "Foe Slayer"), ("Mal des Jägers verursacht W10 statt W6.", "Hunter's mark deals d10 instead of d6."))]})),
 dict(key="rogue", name=("Schurke", "Rogue"), hd="d8", primary="dex", caster=False, saves=abil("dex", "int"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen, Kriegswaffen mit Finesse oder leicht", "Simple weapons, martial weapons with finesse or light"), tools=("Diebeswerkzeug", "Thieves' tools"),
      skill_count=4, skill_options=skills("acrobatics", "athletics", "deception", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "sleight", "stealth"),
      desc=("Ein geschickter Experte für Heimlichkeit und Präzision.", "A dexterous expert in stealth and precision."),
      features=lv({1: [F(("Expertise", "Expertise"), ("Doppelter Übungsbonus in zwei Fertigkeiten (Stufe 6: zwei weitere).", "Double proficiency in two skills (two more at level 6)."), [{"type": "skill", "count": 2}]),
                       F(("Hinterhältiger Angriff", "Sneak Attack"), ("Einmal pro Zug +1W6 (steigt) bei Vorteil oder Verbündetem am Ziel.", "Once per turn +1d6 (scales) with advantage or an ally next to the target.")),
                       F(("Diebessprache", "Thieves' Cant"), ("Geheimsprache der Unterwelt und eine weitere Sprache.", "Secret underworld language and one more language.")), WM(2)],
                   2: [F(("Raffinierte Aktion", "Cunning Action"), ("Spurt, Rückzug oder Verstecken als Bonusaktion.", "Dash, Disengage or Hide as a bonus action."))],
                   3: [SUB("Schurken-Unterklasse", "Rogue Subclass"), F(("Ruhiges Zielen", "Steady Aim"), ("Bonusaktion: Vorteil auf den nächsten Angriff, wenn du dich nicht bewegst.", "Bonus action: advantage on your next attack if you don't move."))],
                   5: [F(("Raffinierter Schlag", "Cunning Strike"), ("Würfel des Hinterhalts für Gift, Umstoßen oder Rückzug eintauschen.", "Trade Sneak Attack dice for poison, trip or withdraw.")),
                       F(("Unheimliches Ausweichen", "Uncanny Dodge"), ("Reaktion: Schaden eines Angriffs halbieren.", "Reaction: halve an attack's damage."))],
                   7: [F(("Entrinnen", "Evasion"), ("GES-Rettungswürfe für halben Schaden: Erfolg = kein Schaden.", "DEX saves for half damage: success = no damage.")),
                       F(("Verlässliches Talent", "Reliable Talent"), ("Geübte Proben: 9 oder weniger zählt als 10.", "Proficient checks: treat 9 or lower as 10."))],
                   9: [SC], 10: [ASI], 11: [F(("Verbesserter raffinierter Schlag", "Improved Cunning Strike"), ("Zwei Effekte gleichzeitig.", "Two effects at once."))], 13: [SC],
                   14: [F(("Hinterlistige Schläge", "Devious Strikes"), ("Neue Effekte: Benommen, Bewusstlos, Verschleiert.", "New effects: Daze, Knock Out, Obscure."))],
                   15: [F(("Schlüpfriger Geist", "Slippery Mind"), ("Geübt in WEI- und CHA-Rettungswürfen.", "Proficient in WIS and CHA saves."))], 17: [SC],
                   18: [F(("Schwer zu fassen", "Elusive"), ("Angriffe gegen dich haben nie Vorteil.", "Attacks against you never have advantage."))],
                   20: [F(("Glückstreffer", "Stroke of Luck"), ("Fehlgeschlagenen W20-Wurf in eine 20 verwandeln (einmal pro Rast).", "Turn a failed d20 test into a 20 (once per rest)."))]})),
 dict(key="sorcerer", name=("Hexenmeister", "Sorcerer"), hd="d6", primary="cha", caster=True, saves=abil("con", "cha"),
      armor=("Keine", "None"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "deception", "insight", "intimidation", "persuasion", "religion"), desc=("Ein Magier mit angeborener, roher Magie.", "A caster of innate, raw magic."),
      features=lv({1: [SPELLS(("CHA", "CHA")), F(("Angeborene Zauberei", "Innate Sorcery"), ("Bonusaktion: 1 Minute höherer Zauber-SG und Vorteil auf Zauberangriffe (zweimal pro langer Rast).", "Bonus action: 1 minute of higher spell DC and advantage on spell attacks (twice per long rest)."))],
                   2: [F(("Quelle der Magie", "Font of Magic"), ("Zauberpunkte = Stufe; mit Zauberplätzen tauschen.", "Sorcery points equal to level; trade with spell slots.")),
                       F(("Metamagie", "Metamagic"), ("Zwei Metamagie-Optionen (weitere auf Stufe 10 und 17).", "Two metamagic options (more at levels 10 and 17)."))],
                   3: [SUB("Hexenmeister-Unterklasse", "Sorcerer Subclass")], 5: [F(("Zauberische Erholung", "Sorcerous Restoration"), ("Nach kurzer Rast Zauberpunkte bis zur halben Stufe zurück.", "Regain sorcery points up to half your level on a short rest."))],
                   6: [SC], 7: [F(("Verkörperte Zauberei", "Sorcery Incarnate"), ("Angeborene Zauberei für Zauberpunkte; zwei Metamagien pro Zauber.", "Innate Sorcery for sorcery points; two metamagics per spell."))], 14: [SC], 18: [SC],
                   20: [F(("Arkane Apotheose", "Arcane Apotheosis"), ("Während angeborener Zauberei einmal pro Zug Metamagie kostenlos.", "During Innate Sorcery, one free metamagic per turn."))]})),
 dict(key="warlock", name=("Hexer", "Warlock"), hd="d8", primary="cha", caster=True, saves=abil("wis", "cha"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"), desc=("Ein Suchender verbotenen Wissens im Pakt mit einer Macht.", "A seeker of forbidden lore bound to a patron."),
      features=lv({1: [F(("Schauerliche Anrufungen", "Eldritch Invocations"), ("Anrufungen mit besonderen Fähigkeiten (mehr mit der Stufe).", "Invocations granting special abilities (more as you level).")),
                       F(("Paktmagie", "Pact Magic"), ("Wenige Zauberplätze höchsten Grades, zurück nach kurzer Rast. Attribut: CHA.", "A few top-level slots that return on a short rest. Ability: CHA."))],
                   2: [F(("Magische Gerissenheit", "Magical Cunning"), ("1 Minute: halbe Paktzauberplätze zurück (einmal pro langer Rast).", "1 minute: regain half your pact slots (once per long rest)."))],
                   3: [SUB("Hexer-Unterklasse", "Warlock Subclass")], 6: [SC],
                   9: [F(("Schutzherrn kontaktieren", "Contact Patron"), ("Kontakt zu einer anderen Ebene wirken, ohne Platz.", "Cast contact other plane without a slot."))], 10: [SC],
                   11: [F(("Mystisches Arkanum", "Mystic Arcanum"), ("Ein Zauber 6. Grades einmal pro langer Rast (7.–9. Grad auf 13/15/17).", "One 6th-level spell once per long rest (7th–9th at 13/15/17)."))], 14: [SC],
                   20: [F(("Schauerlicher Meister", "Eldritch Master"), ("Magische Gerissenheit stellt alle Paktplätze wieder her.", "Magical Cunning restores all pact slots."))]})),
 dict(key="wizard", name=("Magier", "Wizard"), hd="d6", primary="int", caster=True, saves=abil("int", "wis"),
      armor=("Keine", "None"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "history", "insight", "investigation", "medicine", "nature", "religion"), desc=("Ein Gelehrter der arkanen Magie.", "A scholar of arcane magic."),
      features=lv({1: [SPELLS(("INT", "INT")), F(("Ritualkundig", "Ritual Adept"), ("Ritualzauber aus dem Zauberbuch ohne Vorbereitung.", "Cast ritual spells from your book without preparing them.")),
                       F(("Arkane Erholung", "Arcane Recovery"), ("Bei kurzer Rast Zauberplätze bis zur halben Stufe zurück (einmal am Tag).", "Recover spell slots up to half your level on a short rest (once a day)."))],
                   2: [F(("Gelehrter", "Scholar"), ("Expertise in einer Wissensfertigkeit.", "Expertise in one knowledge skill."), [{"type": "skill", "count": 1}])],
                   3: [SUB("Magier-Unterklasse", "Wizard Subclass")], 5: [F(("Zauber einprägen", "Memorize Spell"), ("Bei kurzer Rast einen vorbereiteten Zauber tauschen.", "Swap one prepared spell on a short rest."))],
                   6: [SC], 10: [SC], 14: [SC],
                   18: [F(("Zaubermeisterschaft", "Spell Mastery"), ("Je ein Zauber 1. und 2. Grades ohne Platz.", "One 1st- and one 2nd-level spell at will."))],
                   20: [F(("Signaturzauber", "Signature Spells"), ("Zwei Zauber 3. Grades je einmal pro kurzer Rast ohne Platz.", "Two 3rd-level spells, each once per short rest without a slot."))]})),
]

SUBCLASSES = [
 dict(key="berserker", name=("Pfad des Berserkers", "Path of the Berserker"), parent="barbarian", start=3, desc=("Wut als rohe Gewalt.", "Rage as raw violence."),
      features={3: [F(("Raserei", "Frenzy"), ("Rücksichtsloser Angriff im Kampfrausch: Zusatzschaden beim ersten Treffer.", "Reckless Attack while raging: extra damage on your first hit."))],
                6: [F(("Gedankenloser Kampfrausch", "Mindless Rage"), ("Im Kampfrausch immun gegen Bezauberung und Verängstigung.", "Immune to charm and fear while raging."))],
                10: [F(("Vergeltung", "Retaliation"), ("Reaktion: Gegenangriff gegen nahe Angreifer.", "Reaction: strike back at a nearby attacker."))],
                14: [F(("Einschüchternde Präsenz", "Intimidating Presence"), ("Bonusaktion: Feinde in 30 ft verängstigen.", "Bonus action: frighten foes within 30 ft."))]}),
 dict(key="lore", name=("Schule des Wissens", "College of Lore"), parent="bard", start=3, desc=("Sammler von Wissen und Geheimnissen.", "Collectors of knowledge and secrets."),
      features={3: [F(("Zusätzliche Übung", "Bonus Proficiencies"), ("Drei Fertigkeiten deiner Wahl.", "Three skills of your choice."), [{"type": "skill", "count": 3}]),
                    F(("Schneidende Worte", "Cutting Words"), ("Reaktion: Inspirationswürfel von einem gegnerischen Wurf abziehen.", "Reaction: subtract an inspiration die from an enemy roll."))],
                6: [F(("Magische Entdeckungen", "Magical Discoveries"), ("Zwei Zauber aus Kleriker-, Druiden- oder Magierliste.", "Two spells from the cleric, druid or wizard list."), [{"type": "spell", "count": 2}])],
                14: [F(("Unvergleichliches Können", "Peerless Skill"), ("Inspiration auf eigene misslungene Proben.", "Use inspiration on your own failed checks."))]}),
 dict(key="life", name=("Domäne des Lebens", "Life Domain"), parent="cleric", start=3, desc=("Heilende Kraft des Lebens.", "The healing power of life."),
      features={3: [F(("Jünger des Lebens", "Disciple of Life"), ("Heilzauber heilen zusätzlich 2 + Zaubergrad.", "Healing spells restore an extra 2 + spell level.")),
                    F(("Domänenzauber", "Life Domain Spells"), ("Immer vorbereitet: u. a. Segnen, Wunden heilen.", "Always prepared: e.g. bless, cure wounds.")),
                    F(("Leben bewahren", "Preserve Life"), ("Göttliche Macht: Heilung von 5 × Stufe verteilen.", "Channel Divinity: distribute 5 × level healing."))],
                6: [F(("Gesegneter Heiler", "Blessed Healer"), ("Heilst du andere, heilst du dich selbst.", "Healing others heals you too."))],
                17: [F(("Höchste Heilung", "Supreme Healing"), ("Heilwürfel zählen den Höchstwert.", "Healing dice count as maximum."))]}),
 dict(key="land", name=("Zirkel des Landes", "Circle of the Land"), parent="druid", start=3, desc=("Hüter der Landschaften.", "Keepers of the lands."),
      features={3: [F(("Zirkelzauber", "Circle Spells"), ("Zauber je nach gewähltem Land (Arktis, Küste, Wüste, Wald, Grasland, Gebirge, Sumpf, Unterreich).", "Spells by chosen land (arctic, coast, desert, forest, grassland, mountain, swamp, underdark).")),
                    F(("Hilfe des Landes", "Land's Aid"), ("Tiergestalt nutzen: Schaden in einem Bereich und Heilung eines Verbündeten.", "Spend Wild Shape: damage an area and heal an ally."))],
                6: [F(("Natürliche Erholung", "Natural Recovery"), ("Zauberplätze zurück bei kurzer Rast; ein Zirkelzauber ohne Platz.", "Recover slots on a short rest; one circle spell without a slot."))],
                10: [F(("Schutz der Natur", "Nature's Ward"), ("Immun gegen Vergiftung; Resistenz je nach Land.", "Immune to poisoned; resistance by land."))],
                14: [F(("Zuflucht der Natur", "Nature's Sanctuary"), ("Tiergestalt: schützender Hain aus Bäumen.", "Spend Wild Shape: a protective grove of trees."))]}),
 dict(key="champion", name=("Champion", "Champion"), parent="fighter", start=3, desc=("Körperliche Perfektion.", "Physical perfection."),
      features={3: [F(("Verbesserter kritischer Treffer", "Improved Critical"), ("Kritisch bei 19–20.", "Critical on 19–20.")), F(("Bemerkenswerter Athlet", "Remarkable Athlete"), ("Vorteil auf Initiative und Athletik; Bewegung nach kritischem Treffer.", "Advantage on initiative and Athletics; move after a critical hit."))],
                7: [F(("Zusätzlicher Kampfstil", "Additional Fighting Style"), ("Ein weiteres Kampfstil-Talent.", "Another Fighting Style feat."), [{"type": "fighting_style", "count": 1}])],
                10: [F(("Heldenhafter Krieger", "Heroic Warrior"), ("Ohne Inspiration zu Beginn des Zuges Heldenhafte Inspiration.", "Gain Heroic Inspiration at the start of your turn if you have none."))],
                15: [F(("Überlegener kritischer Treffer", "Superior Critical"), ("Kritisch bei 18–20.", "Critical on 18–20."))],
                18: [F(("Überlebender", "Survivor"), ("Vorteil bei Todesrettungswürfen; Regeneration bei wenig TP.", "Advantage on death saves; regenerate when low on HP."))]}),
 dict(key="openhand", name=("Krieger der offenen Hand", "Warrior of the Open Hand"), aliases=["Weg der offenen Hand"], parent="monk", start=3, desc=("Meister des waffenlosen Kampfes.", "Masters of unarmed combat."),
      features={3: [F(("Technik der offenen Hand", "Open Hand Technique"), ("Schlaghagel: Ziel umwerfen, wegstoßen oder Reaktionen verwehren.", "Flurry of Blows: topple, push or deny reactions."))],
                6: [F(("Ganzheit des Körpers", "Wholeness of Body"), ("Bonusaktion: Kampfkunstwürfel + WEI heilen (WEI-mal pro langer Rast).", "Bonus action: heal a martial arts die + WIS (WIS times per long rest)."))],
                11: [F(("Flinker Schritt", "Fleet Step"), ("Schritt des Windes nach jeder anderen Bonusaktion.", "Step of the Wind after any other bonus action."))],
                17: [F(("Bebende Handfläche", "Quivering Palm"), ("4 Fokus: tödliche Schwingungen, später 10W12 Energieschaden.", "4 focus: lethal vibrations, later 10d12 force damage."))]}),
 dict(key="devotion", name=("Schwur der Hingabe", "Oath of Devotion"), parent="paladin", start=3, desc=("Ideale des edlen Ritters.", "Ideals of the noble knight."),
      features={3: [F(("Schwurzauber", "Oath of Devotion Spells"), ("Immer vorbereitet: u. a. Schutz vor Gut und Böse, Heiligtum.", "Always prepared: e.g. protection from evil and good, sanctuary.")),
                    F(("Geheiligte Waffe", "Sacred Weapon"), ("Göttliche Macht: +CHA auf Angriffe, Waffe leuchtet.", "Channel Divinity: +CHA to attacks, weapon glows."))],
                7: [F(("Aura der Hingabe", "Aura of Devotion"), ("Immun gegen Bezauberung in deiner Aura.", "Immune to charm within your aura."))],
                15: [F(("Schützendes Niederstrecken", "Smite of Protection"), ("Nach Niederstrecken: halbe Deckung für Verbündete in der Aura.", "After a smite: half cover for allies in your aura."))],
                20: [F(("Heiliger Nimbus", "Holy Nimbus"), ("10 Minuten: Licht, Schaden an Feinden, Vorteil gegen Unholde und Untote.", "10 minutes: light, damage to foes, advantage against fiends and undead."))]}),
 dict(key="hunter", name=("Jäger", "Hunter"), parent="ranger", start=3, desc=("Schutz vor den Gefahren der Wildnis.", "Protection from the wild's dangers."),
      features={3: [F(("Wissen des Jägers", "Hunter's Lore"), ("Mal des Jägers enthüllt Resistenzen und Immunitäten.", "Hunter's mark reveals resistances and immunities.")),
                    F(("Beute des Jägers", "Hunter's Prey"), ("Kolossbezwinger oder Hordenbrecher.", "Colossus Slayer or Horde Breaker."))],
                7: [F(("Verteidigungstaktik", "Defensive Tactics"), ("Der Horde entkommen oder Verteidigung gegen Mehrfachangriffe.", "Escape the Horde or Multiattack Defense."))],
                11: [F(("Überlegene Beute", "Superior Hunter's Prey"), ("Mal-Schaden trifft ein zweites nahes Ziel.", "Mark damage also hits a second nearby target."))],
                15: [F(("Überlegene Jägerverteidigung", "Superior Hunter's Defense"), ("Reaktion: Resistenz gegen den auslösenden Schaden.", "Reaction: resistance to the triggering damage."))]}),
 dict(key="thief", name=("Dieb", "Thief"), parent="rogue", start=3, desc=("Einbrecher und Fassadenkletterer.", "Burglars and second-story artists."),
      features={3: [F(("Flinke Hände", "Fast Hands"), ("Fingerfertigkeit oder Gegenstand benutzen als Bonusaktion.", "Sleight of Hand or Use an Object as a bonus action.")),
                    F(("Fassadenkletterer", "Second-Story Work"), ("Klettergeschwindigkeit; Sprünge mit GES.", "Climb speed; jump using DEX."))],
                9: [F(("Überragende Heimlichkeit", "Supreme Sneak"), ("Raffinierter Schlag: Heimlicher Angriff ohne Versteck zu verlieren.", "Cunning Strike option: Stealth Attack."))],
                13: [F(("Magische Gegenstände nutzen", "Use Magic Device"), ("Mehr Einstimmungen; Schriftrollen benutzen.", "More attunement; use spell scrolls."))],
                17: [F(("Diebesreflexe", "Thief's Reflexes"), ("Zwei Züge in der ersten Runde.", "Two turns in the first round."))]}),
 dict(key="draconic", name=("Drakonische Zauberei", "Draconic Sorcery"), aliases=["Drakonische Blutlinie"], parent="sorcerer", start=3, desc=("Drachenmagie im Blut.", "Dragon magic in the blood."),
      features={3: [F(("Drakonische Widerstandskraft", "Draconic Resilience"), ("+1 TP pro Stufe; RK 10 + GES + CHA ohne Rüstung.", "+1 HP per level; AC 10 + DEX + CHA without armour.")),
                    F(("Drakonische Zauber", "Draconic Spells"), ("Immer vorbereitet: u. a. Furcht, Fliegen.", "Always prepared: e.g. fear, fly."))],
                6: [F(("Elementare Affinität", "Elemental Affinity"), ("Resistenz und +CHA Schaden einer Drachen-Schadensart.", "Resistance and +CHA damage of a dragon type."), [{"type": "damage_type", "count": 1}])],
                14: [F(("Drachenschwingen", "Dragon Wings"), ("Bonusaktion: Flügel, 1 Stunde Fluggeschwindigkeit.", "Bonus action: wings with a flying speed for 1 hour."))],
                18: [F(("Drachengefährte", "Dragon Companion"), ("Drachen beschwören ohne Materialkomponente.", "Summon dragon without a material component."))]}),
 dict(key="fiend", name=("Unhold-Schutzherr", "Fiend Patron"), aliases=["Der Unhold"], parent="warlock", start=3, desc=("Ein Pakt mit den unteren Ebenen.", "A pact with the lower planes."),
      features={3: [F(("Segen des Dunklen", "Dark One's Blessing"), ("Fällt ein Feind in deiner Nähe auf 0 TP: temporäre TP = CHA + Stufe.", "When a foe near you drops to 0 HP: temporary HP = CHA + level.")),
                    F(("Unholdzauber", "Fiend Spells"), ("Immer vorbereitet: u. a. Brennende Hände, Feuerball.", "Always prepared: e.g. burning hands, fireball."))],
                6: [F(("Glück des Dunklen", "Dark One's Own Luck"), ("+1W10 auf eine Probe oder einen Rettungswurf (CHA-mal pro langer Rast).", "+1d10 to a check or save (CHA times per long rest)."))],
                10: [F(("Unholdische Widerstandskraft", "Fiendish Resilience"), ("Nach jeder Rast Resistenz gegen eine Schadensart.", "After each rest, resistance to one damage type."))],
                14: [F(("Durch die Hölle schleudern", "Hurl Through Hell"), ("Treffer: Ziel durch die Hölle, 8W10 psychischer Schaden.", "On a hit: the target is hurled through hell, 8d10 psychic damage."))]}),
 dict(key="evoker", name=("Hervorrufer", "Evoker"), aliases=["Hervorrufung"], parent="wizard", start=3, desc=("Meister zerstörerischer Energie.", "Masters of destructive energy."),
      features={3: [F(("Hervorrufungs-Gelehrter", "Evocation Savant"), ("Zwei Hervorrufungszauber kostenlos; neue günstiger.", "Two evocation spells free; new ones cheaper.")),
                    F(("Wirksamer Zaubertrick", "Potent Cantrip"), ("Bestandene Rettungswürfe gegen Zaubertricks: halber Schaden.", "Successful saves against cantrips: half damage."))],
                6: [F(("Zauber formen", "Sculpt Spells"), ("Verbündete aus Hervorrufungszaubern aussparen.", "Exclude allies from evocation spells."))],
                10: [F(("Verstärkte Hervorrufung", "Empowered Evocation"), ("+INT auf einen Schadenswurf.", "+INT to one damage roll."))],
                14: [F(("Überladen", "Overchannel"), ("Zauber bis 5. Grad mit Höchstschaden; danach nekrotischer Rückschlag.", "Spells up to 5th level deal maximum damage, with necrotic backlash."))]}),
]

CONDITIONS = [
 (("Blind", "Blinded"), ("Sieht nichts; Angriffe gegen dich mit Vorteil, eigene mit Nachteil.", "Can't see; attacks against you have advantage, yours disadvantage.")),
 (("Bezaubert", "Charmed"), ("Kann den Bezauberer nicht angreifen; er hat Vorteil bei sozialen Proben.", "Can't attack the charmer; it has advantage on social checks.")),
 (("Taub", "Deafened"), ("Hört nichts; Proben, die Hören erfordern, scheitern.", "Can't hear; checks relying on hearing fail.")),
 (("Erschöpft", "Exhaustion"), ("Je Stufe −2 auf W20-Würfe und −5 ft Geschwindigkeit; Stufe 6 bedeutet den Tod.", "Each level: −2 to d20 tests and −5 ft speed; level 6 means death.")),
 (("Verängstigt", "Frightened"), ("Nachteil, solange die Quelle sichtbar ist; kann sich ihr nicht nähern.", "Disadvantage while the source is visible; can't approach it.")),
 (("Gepackt", "Grappled"), ("Geschwindigkeit 0; Nachteil gegen andere als den Greifenden.", "Speed 0; disadvantage against anyone but the grappler.")),
 (("Kampfunfähig", "Incapacitated"), ("Keine Aktionen, Bonusaktionen, Reaktionen; Konzentration endet.", "No actions, bonus actions or reactions; concentration ends.")),
 (("Unsichtbar", "Invisible"), ("Überraschung bei Initiative; eigene Angriffe mit Vorteil, gegen dich mit Nachteil.", "Surprise on initiative; your attacks have advantage, attacks against you disadvantage.")),
 (("Gelähmt", "Paralyzed"), ("Kampfunfähig, keine Bewegung; Nahkampftreffer sind kritisch.", "Incapacitated and can't move; melee hits are critical.")),
 (("Versteinert", "Petrified"), ("Zu Stein; Resistenz gegen allen Schaden, immun gegen Gift.", "Turned to stone; resistance to all damage, immune to poison.")),
 (("Vergiftet", "Poisoned"), ("Nachteil auf Angriffe und Attributsproben.", "Disadvantage on attacks and ability checks.")),
 (("Liegend", "Prone"), ("Kriechen; Nahkampf gegen dich mit Vorteil, Fernkampf mit Nachteil.", "Crawl only; melee against you has advantage, ranged disadvantage.")),
 (("Festgesetzt", "Restrained"), ("Geschwindigkeit 0; Angriffe gegen dich mit Vorteil, eigene mit Nachteil.", "Speed 0; attacks against you have advantage, yours disadvantage.")),
 (("Betäubt", "Stunned"), ("Kampfunfähig; Angriffe gegen dich mit Vorteil.", "Incapacitated; attacks against you have advantage.")),
 (("Bewusstlos", "Unconscious"), ("Kampfunfähig und liegend; Nahkampftreffer sind kritisch.", "Incapacitated and prone; melee hits are critical.")),
]
LANGUAGES = [
 (("Gemeinsprache", "Common"), "Standard", ("Gemeinsprache", "Common"), ("Die meisten Völker", "Most peoples")),
 (("Gebärdensprache", "Common Sign Language"), "Standard", ("—", "—"), ("Überall verbreitet", "Widespread")),
 (("Drakonisch", "Draconic"), "Standard", ("Drakonisch", "Draconic"), ("Drachen, Drachenblütige", "Dragons, dragonborn")),
 (("Zwergisch", "Dwarvish"), "Standard", ("Zwergisch", "Dwarvish"), ("Zwerge", "Dwarves")),
 (("Elfisch", "Elvish"), "Standard", ("Elfisch", "Elvish"), ("Elfen", "Elves")),
 (("Riesisch", "Giant"), "Standard", ("Zwergisch", "Dwarvish"), ("Riesen", "Giants")),
 (("Gnomisch", "Gnomish"), "Standard", ("Zwergisch", "Dwarvish"), ("Gnome", "Gnomes")),
 (("Goblinisch", "Goblin"), "Standard", ("Zwergisch", "Dwarvish"), ("Goblinoide", "Goblinoids")),
 (("Halblingisch", "Halfling"), "Standard", ("Gemeinsprache", "Common"), ("Halblinge", "Halflings")),
 (("Orkisch", "Orc"), "Standard", ("Zwergisch", "Dwarvish"), ("Orks", "Orcs")),
 (("Abyssisch", "Abyssal"), "Selten", ("Infernalisch", "Infernal"), ("Dämonen", "Demons")),
 (("Celestisch", "Celestial"), "Selten", ("Celestisch", "Celestial"), ("Celestische Wesen", "Celestials")),
 (("Tiefensprache", "Deep Speech"), "Selten", ("—", "—"), ("Aberrationen", "Aberrations")),
 (("Druidisch", "Druidic"), "Selten", ("Druidisch", "Druidic"), ("Druiden", "Druids")),
 (("Infernalisch", "Infernal"), "Selten", ("Infernalisch", "Infernal"), ("Teufel", "Devils")),
 (("Urtümlich", "Primordial"), "Selten", ("Zwergisch", "Dwarvish"), ("Elementare", "Elementals")),
 (("Sylvanisch", "Sylvan"), "Selten", ("Elfisch", "Elvish"), ("Feenwesen", "Fey")),
 (("Diebessprache", "Thieves' Cant"), "Selten", ("—", "—"), ("Schurken", "Rogues")),
 (("Gemeinsprache der Unterreiche", "Undercommon"), "Selten", ("Elfisch", "Elvish"), ("Bewohner des Unterreichs", "Underdark dwellers")),
]
