"""SRD 5.1 (Regeln 2014) – eigene Kurzfassungen, CC-BY-4.0-Quelle.
Unterrassen des SRD sind im jeweiligen Volk enthalten (Hügelzwerg, Hochelf,
Leichtfuß-Halbling, Felsengnom)."""
from common import F, ASI, SUBCLASS_FEATURE, abil, skills, ALL_SKILLS

DV = lambda ft=60: F(("Dunkelsicht", "Darkvision"),
    (f"Im Dämmerlicht auf {ft} ft wie bei hellem Licht, im Dunkeln wie im Dämmerlicht (nur Graustufen).",
     f"Within {ft} ft you see in dim light as if bright and in darkness as if dim (shades of grey only)."))

RACES = [
 dict(key="dwarf", name=("Zwerg", "Dwarf"), size=("Mittel", "Medium"), speed=25, darkvision=60,
      asi=("+2 KON, +1 WEI", "+2 CON, +1 WIS"), languages=("Gemeinsprache, Zwergisch", "Common, Dwarvish"),
      desc=("Robuste Krieger und Handwerker aus den Bergen (Hügelzwerg).", "Hardy warriors and crafters of the mountains (hill dwarf)."),
      traits=[DV(),
        F(("Zwergische Widerstandskraft", "Dwarven Resilience"), ("Vorteil bei Rettungswürfen gegen Gift, Resistenz gegen Giftschaden.", "Advantage on saves against poison and resistance to poison damage.")),
        F(("Zwergische Kampfausbildung", "Dwarven Combat Training"), ("Geübt mit Streitaxt, Handaxt, leichtem Hammer und Kriegshammer.", "Proficient with battleaxe, handaxe, light hammer and warhammer.")),
        F(("Werkzeugübung", "Tool Proficiency"), ("Geübt mit Schmiede-, Brauer- oder Steinmetzwerkzeug (eine Wahl).", "Proficient with smith's, brewer's or mason's tools (choose one)."), [{"type": "tool", "count": 1}]),
        F(("Steingespür", "Stonecunning"), ("Doppelter Übungsbonus auf Geschichte-Proben zu Steinarbeiten.", "Double proficiency bonus on History checks about stonework.")),
        F(("Zwergische Zähigkeit", "Dwarven Toughness"), ("+1 Trefferpunkt-Maximum pro Stufe.", "+1 hit point maximum per level."))]),
 dict(key="elf", name=("Elf", "Elf"), size=("Mittel", "Medium"), speed=30, darkvision=60,
      asi=("+2 GES, +1 INT", "+2 DEX, +1 INT"), languages=("Gemeinsprache, Elfisch, +1 Sprache", "Common, Elvish, +1 language"),
      desc=("Anmutige, langlebige Wesen mit starker Verbindung zur Magie (Hochelf).", "Graceful, long-lived beings with a strong bond to magic (high elf)."),
      traits=[DV(),
        F(("Scharfe Sinne", "Keen Senses"), ("Geübt in Wahrnehmung.", "Proficient in Perception.")),
        F(("Feenblut", "Fey Ancestry"), ("Vorteil gegen Bezauberung; Magie kann dich nicht einschläfern.", "Advantage against being charmed; magic can't put you to sleep.")),
        F(("Trance", "Trance"), ("4 Stunden Meditation ersetzen 8 Stunden Schlaf.", "4 hours of meditation replace 8 hours of sleep.")),
        F(("Elfische Waffenausbildung", "Elf Weapon Training"), ("Geübt mit Langschwert, Kurzschwert, Kurz- und Langbogen.", "Proficient with longsword, shortsword, shortbow and longbow.")),
        F(("Zaubertrick", "Cantrip"), ("Ein Zaubertrick der Magier-Liste; Attribut: INT.", "One wizard cantrip; spellcasting ability: INT."), [{"type": "cantrip", "count": 1}]),
        F(("Zusätzliche Sprache", "Extra Language"), ("Eine weitere Sprache deiner Wahl.", "One additional language of your choice."), [{"type": "language", "count": 1}])]),
 dict(key="halfling", name=("Halbling", "Halfling"), size=("Klein", "Small"), speed=25, darkvision=0,
      asi=("+2 GES, +1 CHA", "+2 DEX, +1 CHA"), languages=("Gemeinsprache, Halblingisch", "Common, Halfling"),
      desc=("Kleine, gesellige Leute mit erstaunlichem Glück (Leichtfuß).", "Small, sociable folk with remarkable luck (lightfoot)."),
      traits=[
        F(("Glückspilz", "Lucky"), ("Eine gewürfelte 1 bei Angriff, Probe oder Rettungswurf darfst du neu würfeln.", "Reroll a natural 1 on an attack, check or save.")),
        F(("Tapfer", "Brave"), ("Vorteil bei Rettungswürfen gegen Verängstigung.", "Advantage on saves against being frightened.")),
        F(("Halblings-Gewandtheit", "Halfling Nimbleness"), ("Du kannst dich durch den Raum größerer Kreaturen bewegen.", "You can move through the space of any larger creature.")),
        F(("Natürlich verstohlen", "Naturally Stealthy"), ("Verstecken ist möglich, wenn dich nur eine größere Kreatur verdeckt.", "You can hide when obscured only by a larger creature."))]),
 dict(key="human", name=("Mensch", "Human"), size=("Mittel", "Medium"), speed=30, darkvision=0,
      asi=("+1 auf alle Attribute", "+1 to all ability scores"), languages=("Gemeinsprache, +1 Sprache", "Common, +1 language"),
      desc=("Ehrgeizig und vielseitig – das verbreitetste Volk.", "Ambitious and versatile – the most widespread people."),
      traits=[F(("Vielseitig", "Versatile"), ("+1 auf jedes Attribut.", "+1 to every ability score.")),
              F(("Zusätzliche Sprache", "Extra Language"), ("Eine weitere Sprache deiner Wahl.", "One additional language of your choice."), [{"type": "language", "count": 1}])]),
 dict(key="dragonborn", name=("Drachenblut", "Dragonborn"), size=("Mittel", "Medium"), speed=30, darkvision=0,
      asi=("+2 STR, +1 CHA", "+2 STR, +1 CHA"), languages=("Gemeinsprache, Drakonisch", "Common, Draconic"),
      desc=("Stolze Nachfahren von Drachen mit Odemwaffe.", "Proud descendants of dragons with a breath weapon."),
      traits=[
        F(("Drachenahnen", "Draconic Ancestry"), ("Drachenart wählen – sie bestimmt Schadensart und Form der Odemwaffe.", "Choose a dragon type – it sets your damage type and breath shape."), [{"type": "damage_type", "count": 1}]),
        F(("Odemwaffe", "Breath Weapon"), ("Aktion: 2W6 Schaden (ab Stufe 6/11/16: 3W6/4W6/5W6), Rettungswurf SG 8 + KON + Übungsbonus. Einmal pro Rast.", "Action: 2d6 damage (3d6/4d6/5d6 at levels 6/11/16), save DC 8 + CON + proficiency. Once per rest.")),
        F(("Schadensresistenz", "Damage Resistance"), ("Resistenz gegen die Schadensart deiner Drachenahnen.", "Resistance to your ancestry's damage type."))]),
 dict(key="gnome", name=("Gnom", "Gnome"), size=("Klein", "Small"), speed=25, darkvision=60,
      asi=("+2 INT, +1 KON", "+2 INT, +1 CON"), languages=("Gemeinsprache, Gnomisch", "Common, Gnomish"),
      desc=("Neugierige Tüftler und Erfinder (Felsengnom).", "Curious tinkerers and inventors (rock gnome)."),
      traits=[DV(),
        F(("Gnomische Gerissenheit", "Gnome Cunning"), ("Vorteil bei INT-, WEI- und CHA-Rettungswürfen gegen Magie.", "Advantage on INT, WIS and CHA saves against magic.")),
        F(("Kunde der Handwerker", "Artificer's Lore"), ("Doppelter Übungsbonus auf Geschichte-Proben zu magischen und technischen Gegenständen.", "Double proficiency bonus on History checks about magic items and devices.")),
        F(("Bastler", "Tinker"), ("Mit Bastlerwerkzeug kleine mechanische Spielereien bauen.", "Build small clockwork devices with tinker's tools."))]),
 dict(key="halfelf", name=("Halb-Elf", "Half-Elf"), aliases=["Halbelf"], size=("Mittel", "Medium"), speed=30, darkvision=60,
      asi=("+2 CHA, +1 auf zwei andere", "+2 CHA, +1 to two others"), languages=("Gemeinsprache, Elfisch, +1 Sprache", "Common, Elvish, +1 language"),
      desc=("Zwischen zwei Welten – charmant und anpassungsfähig.", "Between two worlds – charming and adaptable."),
      traits=[DV(),
        F(("Feenblut", "Fey Ancestry"), ("Vorteil gegen Bezauberung; Magie kann dich nicht einschläfern.", "Advantage against being charmed; magic can't put you to sleep.")),
        F(("Vielseitige Fertigkeiten", "Skill Versatility"), ("Geübt in zwei Fertigkeiten deiner Wahl.", "Proficient in two skills of your choice."), [{"type": "skill", "count": 2}]),
        F(("Attributsbonus", "Ability Score Increase"), ("+1 auf zwei Attribute deiner Wahl (außer CHA).", "+1 to two ability scores of your choice (not CHA)."), [{"type": "ability", "count": 2}])]),
 dict(key="halforc", name=("Halb-Ork", "Half-Orc"), aliases=["Halbork"], size=("Mittel", "Medium"), speed=30, darkvision=60,
      asi=("+2 STR, +1 KON", "+2 STR, +1 CON"), languages=("Gemeinsprache, Orkisch", "Common, Orc"),
      desc=("Kraftvoll und unbeugsam.", "Powerful and unyielding."),
      traits=[DV(),
        F(("Bedrohlich", "Menacing"), ("Geübt in Einschüchtern.", "Proficient in Intimidation.")),
        F(("Unermüdliche Ausdauer", "Relentless Endurance"), ("Fällst du auf 0 TP, bleibst du stattdessen bei 1 TP. Einmal pro langer Rast.", "When reduced to 0 HP you drop to 1 instead. Once per long rest.")),
        F(("Wilde Angriffe", "Savage Attacks"), ("Bei einem kritischen Nahkampftreffer einen zusätzlichen Waffenwürfel.", "Roll one extra weapon die on a melee critical hit."))]),
 dict(key="tiefling", name=("Tiefling", "Tiefling"), size=("Mittel", "Medium"), speed=30, darkvision=60,
      asi=("+2 CHA, +1 INT", "+2 CHA, +1 INT"), languages=("Gemeinsprache, Infernalisch", "Common, Infernal"),
      desc=("Nachfahren eines höllischen Erbes mit angeborener Magie.", "Heirs of an infernal legacy with innate magic."),
      traits=[DV(),
        F(("Höllische Resistenz", "Hellish Resistance"), ("Resistenz gegen Feuerschaden.", "Resistance to fire damage.")),
        F(("Infernalisches Erbe", "Infernal Legacy"), ("Zaubertrick Thaumaturgie; ab Stufe 3 Höllischer Tadel, ab Stufe 5 Dunkelheit (je 1× pro langer Rast). Attribut: CHA.", "Thaumaturgy cantrip; hellish rebuke at level 3 and darkness at level 5 (each once per long rest). Ability: CHA."))]),
]

# ── Klassen ─────────────────────────────────────────────────────────────────
def SC(n): return SUBCLASS_FEATURE(n)
FS = F(("Kampfstil", "Fighting Style"), ("Einen Kampfstil wählen (z. B. Bogenschießen, Verteidigung, Duellieren).", "Choose a fighting style (e.g. Archery, Defense, Dueling)."), [{"type": "fighting_style", "count": 1}])
EXTRA = F(("Zusätzlicher Angriff", "Extra Attack"), ("Mit der Angriffsaktion zweimal angreifen.", "Attack twice when you take the Attack action."))
SPELLS = lambda a: F(("Zauberwirken", "Spellcasting"), (f"Zauber aus der Klassenliste wirken. Attribut: {a[0]}.", f"Cast spells from your class list. Ability: {a[1]}."))
P_PATH, P_COL, P_DOM, P_CIR, P_ARC, P_TRA, P_OATH, P_RAN, P_ROG, P_ORI, P_PAT, P_SCH = (
 ("Pfad", "path"), ("Schule", "college"), ("Domäne", "domain"), ("Zirkel", "circle"), ("Archetyp", "archetype"), ("Tradition", "tradition"),
 ("Eid", "oath"), ("Archetyp", "archetype"), ("Archetyp", "archetype"), ("Herkunft", "origin"), ("Schutzherr", "patron"), ("Schule", "school"))

def asi_levels(levels, extra=None):
    out = {l: [ASI] for l in levels}
    for l, fs in (extra or {}).items(): out.setdefault(l, []); out[l] = fs + out[l]
    return out

CLASSES = [
 dict(key="barbarian", name=("Barbar", "Barbarian"), hd="d12", primary="str", caster=False, saves=abil("str", "con"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("animal", "athletics", "intimidation", "nature", "perception", "survival"),
      desc=("Ein wilder Krieger, angetrieben von urtümlicher Wut.", "A fierce warrior driven by primal rage."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Kampfrausch", "Rage"), ("Bonusaktion: Vorteil auf STR-Proben und -Rettungswürfe, Bonusschaden, Resistenz gegen Hieb-, Stich- und Wuchtschaden.", "Bonus action: advantage on STR checks and saves, bonus damage, resistance to slashing, piercing and bludgeoning.")),
            F(("Ungerüstete Verteidigung", "Unarmored Defense"), ("Ohne Rüstung: RK 10 + GES + KON.", "Without armour: AC 10 + DEX + CON."))],
        2: [F(("Rücksichtsloser Angriff", "Reckless Attack"), ("Vorteil auf STR-Nahkampfangriffe – Angriffe gegen dich haben ebenfalls Vorteil.", "Advantage on STR melee attacks – attacks against you also have advantage.")),
            F(("Gefahrensinn", "Danger Sense"), ("Vorteil bei GES-Rettungswürfen gegen sichtbare Effekte.", "Advantage on DEX saves against effects you can see."))],
        3: [F(("Pfad des Urinstinkts", "Primal Path"), ("Wähle deinen Pfad (Unterklasse).", "Choose your path (subclass)."), [{"type": "subclass", "count": 1}])],
        5: [EXTRA, F(("Schnelle Bewegung", "Fast Movement"), ("+10 ft Geschwindigkeit ohne schwere Rüstung.", "+10 ft speed without heavy armour."))],
        6: [SC(P_PATH)], 7: [F(("Wilder Instinkt", "Feral Instinct"), ("Vorteil auf Initiative; im Kampfrausch nicht überraschbar.", "Advantage on initiative; can't be surprised while raging."))],
        9: [F(("Brutaler kritischer Treffer", "Brutal Critical"), ("+1 Waffenwürfel bei kritischen Nahkampftreffern (Stufe 13: +2, Stufe 17: +3).", "+1 weapon die on melee critical hits (+2 at level 13, +3 at level 17)."))],
        10: [SC(P_PATH)], 11: [F(("Unerbittlicher Kampfrausch", "Relentless Rage"), ("Fällst du im Kampfrausch auf 0 TP: KON-Rettungswurf SG 10, bei Erfolg 1 TP (SG steigt je Einsatz um 5).", "If you drop to 0 HP while raging: CON save DC 10 to stay at 1 HP (DC +5 per use)."))],
        14: [SC(P_PATH)], 15: [F(("Anhaltender Kampfrausch", "Persistent Rage"), ("Der Kampfrausch endet nur, wenn du bewusstlos wirst oder ihn beendest.", "Your rage only ends if you fall unconscious or choose to end it."))],
        18: [F(("Unbezwingbare Kraft", "Indomitable Might"), ("STR-Proben mindestens in Höhe deines STR-Werts.", "STR checks are at least equal to your STR score."))],
        20: [F(("Urgewaltiger Champion", "Primal Champion"), ("+4 STR und +4 KON, Höchstwert 24.", "+4 STR and +4 CON, maximum 24."))]})),
 dict(key="bard", name=("Barde", "Bard"), hd="d8", primary="cha", caster=True, saves=abil("dex", "cha"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen, Handarmbrust, Langschwert, Rapier, Kurzschwert", "Simple weapons, hand crossbow, longsword, rapier, shortsword"),
      tools=("Drei Musikinstrumente", "Three musical instruments"), skill_count=3, skill_options=skills(*ALL_SKILLS),
      desc=("Magischer Geschichtenerzähler, der Verbündete inspiriert.", "A magical storyteller who inspires allies."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [SPELLS(("CHA", "CHA")), F(("Bardische Inspiration", "Bardic Inspiration"), ("Bonusaktion: Ein Verbündeter erhält einen W6 für einen Wurf (W8/W10/W12 ab Stufe 5/10/15). CHA-mal pro langer Rast.", "Bonus action: an ally gains a d6 for a roll (d8/d10/d12 at levels 5/10/15). CHA times per long rest."))],
        2: [F(("Alleskönner", "Jack of All Trades"), ("Halber Übungsbonus auf ungeübte Attributsproben.", "Half proficiency bonus on unproficient ability checks.")),
            F(("Lied der Erholung", "Song of Rest"), ("Bei kurzer Rast +1W6 Heilung für Verbündete (steigt mit der Stufe).", "During a short rest allies heal an extra 1d6 (increases with level)."))],
        3: [F(("Bardenschule", "Bard College"), ("Wähle deine Schule (Unterklasse).", "Choose your college (subclass)."), [{"type": "subclass", "count": 1}]),
            F(("Expertise", "Expertise"), ("Doppelter Übungsbonus in zwei Fertigkeiten (Stufe 10: zwei weitere).", "Double proficiency in two skills (two more at level 10)."), [{"type": "skill", "count": 2}])],
        5: [F(("Quell der Inspiration", "Font of Inspiration"), ("Bardische Inspiration erneuert sich auch nach kurzer Rast.", "Bardic Inspiration also recovers on a short rest."))],
        6: [F(("Gegenzauber-Lied", "Countercharm"), ("Aktion: Verbündete in 30 ft erhalten Vorteil gegen Verängstigung und Bezauberung.", "Action: allies within 30 ft gain advantage against being frightened or charmed.")), SC(P_COL)],
        10: [F(("Magische Geheimnisse", "Magical Secrets"), ("Zwei Zauber aus beliebigen Klassenlisten lernen (auch Stufe 14 und 18).", "Learn two spells from any class list (again at levels 14 and 18)."), [{"type": "spell", "count": 2}])],
        14: [SC(P_COL)], 20: [F(("Überlegene Inspiration", "Superior Inspiration"), ("Ohne Inspiration bei Initiative erhältst du eine zurück.", "If you have no inspiration left when rolling initiative, you regain one."))]})),
 dict(key="cleric", name=("Kleriker", "Cleric"), hd="d8", primary="wis", caster=True, saves=abil("wis", "cha"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("history", "insight", "medicine", "persuasion", "religion"),
      desc=("Diener einer Gottheit mit göttlicher Magie.", "A servant of a deity wielding divine magic."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [SPELLS(("WEI", "WIS")), F(("Göttliche Domäne", "Divine Domain"), ("Wähle deine Domäne (Unterklasse).", "Choose your domain (subclass)."), [{"type": "subclass", "count": 1}])],
        2: [F(("Göttliche Macht", "Channel Divinity"), ("Einmal pro Rast (Stufe 6: zweimal, Stufe 18: dreimal), u. a. Untote vertreiben.", "Once per rest (twice at 6, three times at 18), e.g. Turn Undead.")), SC(P_DOM)],
        5: [F(("Untote zerstören", "Destroy Undead"), ("Vertriebene schwache Untote werden zerstört (Grenze steigt mit der Stufe).", "Weak undead that are turned are destroyed (threshold rises with level)."))],
        6: [SC(P_DOM)], 8: [SC(P_DOM)],
        10: [F(("Göttliches Eingreifen", "Divine Intervention"), ("Deine Gottheit um Hilfe bitten (Erfolg bei W100 ≤ Stufe; ab Stufe 20 automatisch).", "Call on your deity for aid (succeeds on d100 ≤ level; automatic at level 20)."))],
        17: [SC(P_DOM)]})),
 dict(key="druid", name=("Druide", "Druid"), hd="d8", primary="wis", caster=True, saves=abil("int", "wis"),
      armor=("Leichte & mittlere Rüstung, Schilde (kein Metall)", "Light & medium armour, shields (no metal)"), weapons=("Keule, Dolch, Wurfpfeil, Speer, Kampfstab, Sichel, Schleuder u. a.", "Club, dagger, dart, spear, quarterstaff, sickle, sling and more"),
      tools=("Kräuterkunde-Ausrüstung", "Herbalism kit"), skill_count=2, skill_options=skills("arcana", "animal", "insight", "medicine", "nature", "perception", "religion", "survival"),
      desc=("Hüter der Natur mit wilder Magie und Gestaltwandel.", "A guardian of nature with primal magic and shapechanging."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Druidisch", "Druidic"), ("Die Geheimsprache der Druiden.", "The secret language of druids.")), SPELLS(("WEI", "WIS"))],
        2: [F(("Tiergestalt", "Wild Shape"), ("Zweimal pro kurzer Rast in ein bekanntes Tier verwandeln (Grenzen steigen mit der Stufe).", "Turn into a beast you have seen, twice per short rest (limits rise with level).")),
            F(("Druidenzirkel", "Druid Circle"), ("Wähle deinen Zirkel (Unterklasse).", "Choose your circle (subclass)."), [{"type": "subclass", "count": 1}])],
        6: [SC(P_CIR)], 10: [SC(P_CIR)], 14: [SC(P_CIR)],
        18: [F(("Zeitloser Körper", "Timeless Body"), ("Du alterst nur noch sehr langsam.", "You age very slowly.")), F(("Tierzauber", "Beast Spells"), ("Zauber auch in Tiergestalt wirken.", "Cast spells while in wild shape."))],
        20: [F(("Erzdruide", "Archdruid"), ("Unbegrenzte Tiergestalt; Zauberkomponenten entfallen.", "Unlimited wild shape; ignore many spell components."))]})),
 dict(key="fighter", name=("Kämpfer", "Fighter"), hd="d10", primary="str", caster=False, saves=abil("str", "con"),
      armor=("Alle Rüstungen, Schilde", "All armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("acrobatics", "animal", "athletics", "history", "insight", "intimidation", "perception", "survival"),
      desc=("Meisterlicher Krieger mit vielseitigen Kampftechniken.", "A master of martial combat with versatile techniques."),
      features=asi_levels([4, 6, 8, 12, 14, 16, 19], {
        1: [FS, F(("Durchatmen", "Second Wind"), ("Bonusaktion: 1W10 + Stufe Trefferpunkte heilen. Einmal pro Rast.", "Bonus action: regain 1d10 + level hit points. Once per rest."))],
        2: [F(("Tatendrang", "Action Surge"), ("Eine zusätzliche Aktion in deinem Zug. Einmal pro Rast (ab Stufe 17 zweimal).", "Take one extra action on your turn. Once per rest (twice from level 17)."))],
        3: [F(("Kampfarchetyp", "Martial Archetype"), ("Wähle deinen Archetyp (Unterklasse).", "Choose your archetype (subclass)."), [{"type": "subclass", "count": 1}])],
        5: [EXTRA], 7: [SC(P_ARC)],
        9: [F(("Unbeugsam", "Indomitable"), ("Einen misslungenen Rettungswurf wiederholen. Einmal pro langer Rast (Stufe 13: zweimal, 17: dreimal).", "Reroll a failed saving throw. Once per long rest (twice at 13, three times at 17)."))],
        10: [SC(P_ARC)], 11: [F(("Zusätzlicher Angriff (2)", "Extra Attack (2)"), ("Dreimal angreifen.", "Attack three times."))],
        15: [SC(P_ARC)], 18: [SC(P_ARC)], 20: [F(("Zusätzlicher Angriff (3)", "Extra Attack (3)"), ("Viermal angreifen.", "Attack four times."))]})),
 dict(key="monk", name=("Mönch", "Monk"), hd="d8", primary="dex", caster=False, saves=abil("str", "dex"),
      armor=("Keine", "None"), weapons=("Einfache Waffen, Kurzschwert", "Simple weapons, shortsword"), tools=("Ein Handwerkszeug oder Instrument", "One artisan's tool or instrument"),
      skill_count=2, skill_options=skills("acrobatics", "athletics", "history", "insight", "religion", "stealth"),
      desc=("Disziplinierter Kämpfer mit übernatürlicher Körperbeherrschung.", "A disciplined fighter with supernatural body control."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Ungerüstete Verteidigung", "Unarmored Defense"), ("Ohne Rüstung und Schild: RK 10 + GES + WEI.", "Without armour or shield: AC 10 + DEX + WIS.")),
            F(("Kampfkunst", "Martial Arts"), ("Waffenlose und Mönchswaffen-Angriffe mit GES; Kampfkunstwürfel W4 (steigt); Bonusangriff waffenlos.", "Unarmed and monk weapon attacks use DEX; martial arts die d4 (scales); bonus unarmed strike."))],
        2: [F(("Ki", "Ki"), ("Ki-Punkte = Stufe: Schlaghagel, Geduldige Verteidigung, Schritt des Windes.", "Ki points equal to level: Flurry of Blows, Patient Defense, Step of the Wind.")),
            F(("Ungerüstete Bewegung", "Unarmored Movement"), ("+10 ft Geschwindigkeit (steigt; ab Stufe 9 über Wände und Wasser).", "+10 ft speed (increases; walls and water from level 9)."))],
        3: [F(("Klostertradition", "Monastic Tradition"), ("Wähle deine Tradition (Unterklasse).", "Choose your tradition (subclass)."), [{"type": "subclass", "count": 1}]),
            F(("Geschosse abwehren", "Deflect Missiles"), ("Reaktion: Fernkampfschaden verringern, evtl. zurückwerfen.", "Reaction: reduce ranged weapon damage and possibly throw it back."))],
        4: [F(("Langsamer Fall", "Slow Fall"), ("Reaktion: Fallschaden um das Fünffache der Stufe verringern.", "Reaction: reduce falling damage by five times your level."))],
        5: [EXTRA, F(("Betäubender Schlag", "Stunning Strike"), ("1 Ki nach einem Treffer: KON-Rettungswurf oder betäubt.", "1 ki after a hit: CON save or stunned."))],
        6: [F(("Ki-verstärkte Schläge", "Ki-Empowered Strikes"), ("Waffenlose Angriffe gelten als magisch.", "Unarmed strikes count as magical.")), SC(P_TRA)],
        7: [F(("Entrinnen", "Evasion"), ("Bei GES-Rettungswürfen für halben Schaden: Erfolg = kein Schaden, Misserfolg = halber.", "On DEX saves for half damage: success = none, failure = half.")),
            F(("Geistesruhe", "Stillness of Mind"), ("Aktion: Bezauberung oder Verängstigung an dir beenden.", "Action: end a charm or fear effect on yourself."))],
        10: [F(("Reinheit des Körpers", "Purity of Body"), ("Immun gegen Krankheiten und Gift.", "Immune to disease and poison."))], 11: [SC(P_TRA)],
        13: [F(("Zunge von Sonne und Mond", "Tongue of the Sun and Moon"), ("Du verstehst alle gesprochenen Sprachen.", "You understand all spoken languages."))],
        14: [F(("Diamantene Seele", "Diamond Soul"), ("Geübt in allen Rettungswürfen; 1 Ki für einen neuen Versuch.", "Proficient in all saves; spend 1 ki to reroll one."))],
        15: [F(("Zeitloser Körper", "Timeless Body"), ("Kein Altern mehr durch Magie; kein Essen und Trinken nötig.", "No magical ageing; no need for food or water."))], 17: [SC(P_TRA)],
        18: [F(("Leerer Körper", "Empty Body"), ("4 Ki: 1 Minute unsichtbar mit Resistenz gegen fast alles.", "4 ki: invisible for 1 minute with resistance to almost everything."))],
        20: [F(("Vollkommenes Selbst", "Perfect Self"), ("Mit 0 Ki bei Initiative erhältst du 4 Ki.", "With no ki left when rolling initiative, you regain 4."))]})),
 dict(key="paladin", name=("Paladin", "Paladin"), hd="d10", primary="str", caster=True, saves=abil("wis", "cha"),
      armor=("Alle Rüstungen, Schilde", "All armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("athletics", "insight", "intimidation", "medicine", "persuasion", "religion"),
      desc=("Heiliger Krieger, gebunden an einen Eid.", "A holy warrior bound by an oath."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Göttlicher Sinn", "Divine Sense"), ("Celestische, Unholde und Untote in 60 ft spüren.", "Sense celestials, fiends and undead within 60 ft.")),
            F(("Handauflegen", "Lay on Hands"), ("Heilungspool von 5 × Stufe Trefferpunkten pro langer Rast.", "A pool of 5 × level hit points of healing per long rest."))],
        2: [FS, SPELLS(("CHA", "CHA")), F(("Göttliches Niederstrecken", "Divine Smite"), ("Zauberplatz verbrauchen: +2W8 gleißender Schaden bei einem Nahkampftreffer.", "Spend a spell slot: +2d8 radiant damage on a melee hit."))],
        3: [F(("Göttliche Gesundheit", "Divine Health"), ("Immun gegen Krankheiten.", "Immune to disease.")),
            F(("Heiliger Eid", "Sacred Oath"), ("Wähle deinen Eid (Unterklasse).", "Choose your oath (subclass)."), [{"type": "subclass", "count": 1}])],
        5: [EXTRA], 6: [F(("Aura des Schutzes", "Aura of Protection"), ("Du und Verbündete in 10 ft addieren deinen CHA auf Rettungswürfe.", "You and allies within 10 ft add your CHA to saving throws."))],
        7: [SC(P_OATH)], 10: [F(("Aura des Mutes", "Aura of Courage"), ("Du und Verbündete in 10 ft können nicht verängstigt werden.", "You and allies within 10 ft can't be frightened."))],
        11: [F(("Verbessertes Niederstrecken", "Improved Divine Smite"), ("Alle Nahkampftreffer verursachen +1W8 gleißenden Schaden.", "All melee hits deal +1d8 radiant damage."))],
        14: [F(("Reinigende Berührung", "Cleansing Touch"), ("Aktion: einen Zauber an dir oder einem Verbündeten beenden (CHA-mal pro langer Rast).", "Action: end a spell on yourself or an ally (CHA times per long rest)."))],
        15: [SC(P_OATH)], 18: [F(("Auren-Verbesserung", "Aura Improvements"), ("Deine Auren reichen 30 ft.", "Your auras extend to 30 ft."))], 20: [SC(P_OATH)]})),
 dict(key="ranger", name=("Waldläufer", "Ranger"), hd="d10", primary="dex", caster=True, saves=abil("str", "dex"),
      armor=("Leichte & mittlere Rüstung, Schilde", "Light & medium armour, shields"), weapons=("Einfache & Kriegswaffen", "Simple & martial weapons"), tools=("", ""),
      skill_count=3, skill_options=skills("animal", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"),
      desc=("Jäger der Wildnis mit Spurenlesen und Naturmagie.", "A hunter of the wilds with tracking and nature magic."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Bevorzugter Feind", "Favored Enemy"), ("Vorteil beim Aufspüren und Erinnern an eine Kreaturenart (weitere ab Stufe 6 und 14).", "Advantage to track and recall lore about a creature type (more at levels 6 and 14).")),
            F(("Naturkundiger Entdecker", "Natural Explorer"), ("Vorteile beim Reisen in einem bevorzugten Gelände (weitere ab Stufe 6 und 10).", "Travel benefits in a favoured terrain (more at levels 6 and 10)."))],
        2: [FS, SPELLS(("WEI", "WIS"))],
        3: [F(("Waldläufer-Archetyp", "Ranger Archetype"), ("Wähle deinen Archetyp (Unterklasse).", "Choose your archetype (subclass)."), [{"type": "subclass", "count": 1}]),
            F(("Urtümliches Gespür", "Primeval Awareness"), ("Zauberplatz verbrauchen: bestimmte Kreaturenarten in der Nähe spüren.", "Spend a spell slot to sense certain creature types nearby."))],
        5: [EXTRA], 7: [SC(P_RAN)], 8: [F(("Schritt durch das Land", "Land's Stride"), ("Nichtmagisches schwieriges Gelände kostet keine zusätzliche Bewegung.", "Nonmagical difficult terrain costs no extra movement."))],
        10: [F(("Im Verborgenen", "Hide in Plain Sight"), ("Getarnt +10 auf Heimlichkeit, solange du dich nicht bewegst.", "Camouflaged: +10 to Stealth while you don't move."))], 11: [SC(P_RAN)],
        14: [F(("Verschwinden", "Vanish"), ("Verstecken als Bonusaktion; magisch nicht aufspürbar.", "Hide as a bonus action; can't be tracked by nonmagical means."))], 15: [SC(P_RAN)],
        18: [F(("Wilde Sinne", "Feral Senses"), ("Unsichtbare Kreaturen in 30 ft wahrnehmen.", "Sense invisible creatures within 30 ft."))],
        20: [F(("Feindbezwinger", "Foe Slayer"), ("Einmal pro Zug WEI auf Angriff oder Schaden gegen einen bevorzugten Feind.", "Once per turn add WIS to attack or damage against a favoured enemy."))]})),
 dict(key="rogue", name=("Schurke", "Rogue"), hd="d8", primary="dex", caster=False, saves=abil("dex", "int"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen, Handarmbrust, Langschwert, Rapier, Kurzschwert", "Simple weapons, hand crossbow, longsword, rapier, shortsword"),
      tools=("Diebeswerkzeug", "Thieves' tools"), skill_count=4, skill_options=skills("acrobatics", "athletics", "deception", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "sleight", "stealth"),
      desc=("Geschickter Spezialist für Heimlichkeit und Hinterhalte.", "A skilled specialist in stealth and ambushes."),
      features=asi_levels([4, 8, 10, 12, 16, 19], {
        1: [F(("Expertise", "Expertise"), ("Doppelter Übungsbonus in zwei Fertigkeiten oder Diebeswerkzeug (Stufe 6: zwei weitere).", "Double proficiency in two skills or thieves' tools (two more at level 6)."), [{"type": "skill", "count": 2}]),
            F(("Hinterhältiger Angriff", "Sneak Attack"), ("Einmal pro Zug +1W6 Schaden bei Vorteil oder Verbündetem neben dem Ziel (steigt alle 2 Stufen).", "Once per turn +1d6 damage with advantage or an ally next to the target (increases every 2 levels).")),
            F(("Diebessprache", "Thieves' Cant"), ("Geheimsprache und Zeichen der Unterwelt.", "Secret language and signs of the underworld."))],
        2: [F(("Raffinierte Aktion", "Cunning Action"), ("Spurt, Rückzug oder Verstecken als Bonusaktion.", "Dash, Disengage or Hide as a bonus action."))],
        3: [F(("Schurken-Archetyp", "Roguish Archetype"), ("Wähle deinen Archetyp (Unterklasse).", "Choose your archetype (subclass)."), [{"type": "subclass", "count": 1}])],
        5: [F(("Unheimliches Ausweichen", "Uncanny Dodge"), ("Reaktion: Schaden eines sichtbaren Angriffs halbieren.", "Reaction: halve the damage of an attack you can see."))],
        7: [F(("Entrinnen", "Evasion"), ("Bei GES-Rettungswürfen für halben Schaden: Erfolg = kein Schaden, Misserfolg = halber.", "On DEX saves for half damage: success = none, failure = half."))],
        9: [SC(P_ROG)], 11: [F(("Verlässliches Talent", "Reliable Talent"), ("Bei geübten Proben zählt eine 9 oder weniger als 10.", "On proficient checks, treat a roll of 9 or lower as 10."))], 13: [SC(P_ROG)],
        14: [F(("Blindgespür", "Blindsense"), ("Versteckte und unsichtbare Kreaturen in 10 ft wahrnehmen.", "Sense hidden and invisible creatures within 10 ft."))],
        15: [F(("Schlüpfriger Geist", "Slippery Mind"), ("Geübt in WEI-Rettungswürfen.", "Proficient in WIS saving throws."))], 17: [SC(P_ROG)],
        18: [F(("Schwer zu fassen", "Elusive"), ("Angriffe gegen dich haben nie Vorteil.", "Attacks against you never have advantage."))],
        20: [F(("Glückstreffer", "Stroke of Luck"), ("Einen Fehlschlag in einen Treffer oder eine 20 verwandeln. Einmal pro Rast.", "Turn a miss into a hit or a check into a 20. Once per rest."))]})),
 dict(key="sorcerer", name=("Hexenmeister", "Sorcerer"), aliases=["Zauberer"], hd="d6", primary="cha", caster=True, saves=abil("con", "cha"),
      armor=("Keine", "None"), weapons=("Dolch, Wurfpfeil, Schleuder, Kampfstab, leichte Armbrust", "Dagger, dart, sling, quarterstaff, light crossbow"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "deception", "insight", "intimidation", "persuasion", "religion"),
      desc=("Angeborene Magie aus dem Blut, spontan und kraftvoll.", "Innate magic from the blood, spontaneous and powerful."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [SPELLS(("CHA", "CHA")), F(("Zauberische Herkunft", "Sorcerous Origin"), ("Wähle deine Herkunft (Unterklasse).", "Choose your origin (subclass)."), [{"type": "subclass", "count": 1}])],
        2: [F(("Quelle der Magie", "Font of Magic"), ("Zauberpunkte = Stufe; in Zauberplätze umwandeln und umgekehrt.", "Sorcery points equal to level; convert to and from spell slots."))],
        3: [F(("Metamagie", "Metamagic"), ("Zwei Metamagie-Optionen, um Zauber zu verändern (weitere auf Stufe 10 und 17).", "Two metamagic options to alter spells (more at levels 10 and 17)."))],
        6: [SC(P_ORI)], 14: [SC(P_ORI)], 18: [SC(P_ORI)],
        20: [F(("Zauberische Erholung", "Sorcerous Restoration"), ("Nach kurzer Rast 4 Zauberpunkte zurück.", "Regain 4 sorcery points on a short rest."))]})),
 dict(key="warlock", name=("Hexer", "Warlock"), hd="d8", primary="cha", caster=True, saves=abil("wis", "cha"),
      armor=("Leichte Rüstung", "Light armour"), weapons=("Einfache Waffen", "Simple weapons"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"),
      desc=("Paktgebundener Magier im Dienst eines mächtigen Wesens.", "A pact-bound caster serving a powerful patron."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [F(("Andersweltlicher Schutzherr", "Otherworldly Patron"), ("Wähle deinen Schutzherrn (Unterklasse).", "Choose your patron (subclass)."), [{"type": "subclass", "count": 1}]),
            F(("Paktmagie", "Pact Magic"), ("Wenige Zauberplätze höchsten Grades, die nach kurzer Rast zurückkehren. Attribut: CHA.", "A few top-level spell slots that return on a short rest. Ability: CHA."))],
        2: [F(("Schauerliche Anrufungen", "Eldritch Invocations"), ("Zwei Anrufungen mit besonderen Fähigkeiten (weitere mit der Stufe).", "Two invocations granting special abilities (more as you level)."))],
        3: [F(("Paktgabe", "Pact Boon"), ("Pakt der Kette, der Klinge oder des Folianten.", "Pact of the Chain, Blade or Tome."))],
        6: [SC(P_PAT)], 10: [SC(P_PAT)],
        11: [F(("Mystisches Arkanum", "Mystic Arcanum"), ("Ein Zauber 6. Grades einmal pro langer Rast (7./8./9. Grad auf Stufe 13/15/17).", "One 6th-level spell once per long rest (7th/8th/9th at levels 13/15/17)."))],
        14: [SC(P_PAT)], 20: [F(("Schauerlicher Meister", "Eldritch Master"), ("Eine Minute bitten: alle Paktzauberplätze zurück. Einmal pro langer Rast.", "Spend a minute to regain all pact spell slots. Once per long rest."))]})),
 dict(key="wizard", name=("Magier", "Wizard"), hd="d6", primary="int", caster=True, saves=abil("int", "wis"),
      armor=("Keine", "None"), weapons=("Dolch, Wurfpfeil, Schleuder, Kampfstab, leichte Armbrust", "Dagger, dart, sling, quarterstaff, light crossbow"), tools=("", ""),
      skill_count=2, skill_options=skills("arcana", "history", "insight", "investigation", "medicine", "religion"),
      desc=("Gelehrter der arkanen Magie mit einem Zauberbuch.", "A scholar of arcane magic with a spellbook."),
      features=asi_levels([4, 8, 12, 16, 19], {
        1: [SPELLS(("INT", "INT")), F(("Arkane Erholung", "Arcane Recovery"), ("Einmal am Tag bei kurzer Rast Zauberplätze zurückgewinnen (Gesamtgrad bis zur halben Stufe).", "Once a day on a short rest regain spell slots (total level up to half your level)."))],
        2: [F(("Arkane Tradition", "Arcane Tradition"), ("Wähle deine Schule (Unterklasse).", "Choose your school (subclass)."), [{"type": "subclass", "count": 1}])],
        6: [SC(P_SCH)], 10: [SC(P_SCH)], 14: [SC(P_SCH)],
        18: [F(("Zaubermeisterschaft", "Spell Mastery"), ("Je ein Zauber 1. und 2. Grades ohne Zauberplatz wirkbar.", "Cast one 1st- and one 2nd-level spell at will."))],
        20: [F(("Signaturzauber", "Signature Spells"), ("Zwei Zauber 3. Grades je einmal pro kurzer Rast ohne Zauberplatz.", "Two 3rd-level spells, each once per short rest without a slot."))]})),
]

# ── Unterklassen ────────────────────────────────────────────────────────────
SUBCLASSES = [
 dict(key="berserker", name=("Pfad des Berserkers", "Path of the Berserker"), parent="barbarian", start=3,
      desc=("Wut als reine, rohe Kraft.", "Rage as pure, raw force."),
      features={3: [F(("Raserei", "Frenzy"), ("Im Kampfrausch je Zug ein Nahkampfangriff als Bonusaktion; danach eine Stufe Erschöpfung.", "While raging, one melee attack as a bonus action each turn; gain exhaustion afterwards."))],
                6: [F(("Gedankenloser Kampfrausch", "Mindless Rage"), ("Im Kampfrausch immun gegen Bezauberung und Verängstigung.", "Can't be charmed or frightened while raging."))],
                10: [F(("Einschüchternde Präsenz", "Intimidating Presence"), ("Aktion: eine Kreatur verängstigen (WEI-Rettungswurf).", "Action: frighten a creature (WIS save)."))],
                14: [F(("Vergeltung", "Retaliation"), ("Reaktion: Nahkampfangriff gegen einen Angreifer, der dir in 5 ft Schaden zufügt.", "Reaction: melee attack a creature within 5 ft that damages you."))]}),
 dict(key="lore", name=("Schule des Wissens", "College of Lore"), aliases=["College of Lore"], parent="bard", start=3,
      desc=("Sammler von Geschichten, Geheimnissen und Wahrheiten.", "Collectors of stories, secrets and truths."),
      features={3: [F(("Zusätzliche Übung", "Bonus Proficiencies"), ("Geübt in drei Fertigkeiten deiner Wahl.", "Proficient in three skills of your choice."), [{"type": "skill", "count": 3}]),
                    F(("Schneidende Worte", "Cutting Words"), ("Reaktion: Bardische Inspiration von einem gegnerischen Wurf abziehen.", "Reaction: subtract Bardic Inspiration from an enemy's roll."))],
                6: [F(("Zusätzliche magische Geheimnisse", "Additional Magical Secrets"), ("Zwei Zauber aus beliebigen Klassenlisten.", "Two spells from any class list."), [{"type": "spell", "count": 2}])],
                14: [F(("Unvergleichliches Können", "Peerless Skill"), ("Bardische Inspiration auf eigene Attributsproben anwenden.", "Use Bardic Inspiration on your own ability checks."))]}),
 dict(key="life", name=("Domäne des Lebens", "Life Domain"), aliases=["Leben-Domäne"], parent="cleric", start=1,
      desc=("Positive Energie, die heilt und erhält.", "Positive energy that heals and sustains."),
      features={1: [F(("Zusätzliche Übung", "Bonus Proficiency"), ("Geübt mit schwerer Rüstung.", "Proficient with heavy armour.")),
                    F(("Jünger des Lebens", "Disciple of Life"), ("Heilzauber heilen zusätzlich 2 + Zaubergrad.", "Healing spells restore an extra 2 + spell level.")),
                    F(("Domänenzauber", "Domain Spells"), ("Immer vorbereitet: u. a. Segnen, Wunden heilen, Wiederbeleben.", "Always prepared: e.g. bless, cure wounds, revivify."))],
                2: [F(("Göttliche Macht: Leben bewahren", "Channel Divinity: Preserve Life"), ("Heilung von 5 × Stufe auf Kreaturen in 30 ft verteilen.", "Distribute 5 × level healing among creatures within 30 ft."))],
                6: [F(("Gesegneter Heiler", "Blessed Healer"), ("Heilst du andere, heilst du dich um 2 + Zaubergrad.", "Healing others also heals you for 2 + spell level."))],
                8: [F(("Göttlicher Schlag", "Divine Strike"), ("Einmal pro Zug +1W8 gleißender Schaden mit Waffen (Stufe 14: 2W8).", "Once per turn +1d8 radiant weapon damage (2d8 at level 14)."))],
                17: [F(("Höchste Heilung", "Supreme Healing"), ("Heilwürfel zählen immer den Höchstwert.", "Healing dice always count as their maximum."))]}),
 dict(key="land", name=("Zirkel des Landes", "Circle of the Land"), parent="druid", start=2,
      desc=("Hüter alter Naturorte mit Magie einer Landschaft.", "Keepers of ancient places, drawing magic from a landscape."),
      features={2: [F(("Zusätzlicher Zaubertrick", "Bonus Cantrip"), ("Ein weiterer Druiden-Zaubertrick.", "One additional druid cantrip."), [{"type": "cantrip", "count": 1}]),
                    F(("Natürliche Erholung", "Natural Recovery"), ("Bei kurzer Rast Zauberplätze bis zur halben Stufe zurück (einmal pro langer Rast).", "Recover spell slots up to half your level on a short rest (once per long rest)."))],
                3: [F(("Zirkelzauber", "Circle Spells"), ("Je nach Landschaft zusätzliche, immer vorbereitete Zauber.", "Extra always-prepared spells depending on your land."))],
                6: [F(("Schritt durch das Land", "Land's Stride"), ("Nichtmagisches schwieriges Gelände und Pflanzen behindern dich nicht.", "Nonmagical difficult terrain and plants don't hinder you."))],
                10: [F(("Schutz der Natur", "Nature's Ward"), ("Immun gegen Gift und Krankheit; Elementare und Feen können dich nicht bezaubern oder verängstigen.", "Immune to poison and disease; elementals and fey can't charm or frighten you."))],
                14: [F(("Zuflucht der Natur", "Nature's Sanctuary"), ("Tiere und Pflanzen zögern, dich anzugreifen (WEI-Rettungswurf).", "Beasts and plants hesitate to attack you (WIS save)."))]}),
 dict(key="champion", name=("Champion", "Champion"), parent="fighter", start=3,
      desc=("Meister der körperlichen Perfektion.", "A master of physical perfection."),
      features={3: [F(("Verbesserter kritischer Treffer", "Improved Critical"), ("Kritischer Treffer bei 19–20.", "Critical hit on 19–20."))],
                7: [F(("Bemerkenswerter Athlet", "Remarkable Athlete"), ("Halber Übungsbonus auf ungeübte STR-, GES- und KON-Proben; weitere Sprünge.", "Half proficiency on unproficient STR, DEX and CON checks; longer jumps."))],
                10: [F(("Zusätzlicher Kampfstil", "Additional Fighting Style"), ("Einen zweiten Kampfstil wählen.", "Choose a second fighting style."), [{"type": "fighting_style", "count": 1}])],
                15: [F(("Überlegener kritischer Treffer", "Superior Critical"), ("Kritischer Treffer bei 18–20.", "Critical hit on 18–20."))],
                18: [F(("Überlebender", "Survivor"), ("Mit höchstens halben TP: jeden Zug 5 + KON Trefferpunkte zurück.", "At half HP or less, regain 5 + CON hit points each turn."))]}),
 dict(key="openhand", name=("Weg der offenen Hand", "Way of the Open Hand"), parent="monk", start=3,
      desc=("Meister des waffenlosen Kampfes.", "Masters of unarmed combat."),
      features={3: [F(("Technik der offenen Hand", "Open Hand Technique"), ("Treffer aus dem Schlaghagel: zu Boden werfen, wegstoßen oder Reaktionen verhindern.", "Flurry of Blows hits can knock prone, push away or deny reactions."))],
                6: [F(("Ganzheit des Körpers", "Wholeness of Body"), ("Aktion: 3 × Stufe Trefferpunkte heilen (einmal pro langer Rast).", "Action: heal 3 × level hit points (once per long rest)."))],
                11: [F(("Gelassenheit", "Tranquility"), ("Nach langer Rast Schutz wie durch Heiligtum.", "After a long rest, protected as if by sanctuary."))],
                17: [F(("Bebende Handfläche", "Quivering Palm"), ("3 Ki: Schwingungen, die später 0 TP oder 10W10 nekrotischen Schaden verursachen.", "3 ki: vibrations that later drop a target to 0 HP or deal 10d10 necrotic damage."))]}),
 dict(key="devotion", name=("Schwur der Hingabe", "Oath of Devotion"), parent="paladin", start=3,
      desc=("Das Ideal des edlen Ritters.", "The ideal of the noble knight."),
      features={3: [F(("Schwurzauber", "Oath Spells"), ("Immer vorbereitet: u. a. Schutz vor Gut und Böse, Magie bannen.", "Always prepared: e.g. protection from evil and good, dispel magic.")),
                    F(("Göttliche Macht", "Channel Divinity"), ("Geheiligte Waffe (+CHA auf Angriffe) oder Unheiliges vertreiben.", "Sacred Weapon (+CHA to attacks) or Turn the Unholy."))],
                7: [F(("Aura der Hingabe", "Aura of Devotion"), ("Du und Verbündete in 10 ft können nicht bezaubert werden.", "You and allies within 10 ft can't be charmed."))],
                15: [F(("Reinheit des Geistes", "Purity of Spirit"), ("Dauerhaft geschützt wie durch Schutz vor Gut und Böse.", "Permanently protected as by protection from evil and good."))],
                20: [F(("Heiliger Nimbus", "Holy Nimbus"), ("1 Minute helles Licht, Schaden an Feinden, Schutz vor Unholden und Untoten.", "1 minute of bright light that damages foes and wards against fiends and undead."))]}),
 dict(key="hunter", name=("Jäger", "Hunter"), parent="ranger", start=3,
      desc=("Bollwerk gegen die Schrecken der Wildnis.", "A bulwark against the horrors of the wild."),
      features={3: [F(("Beute des Jägers", "Hunter's Prey"), ("Kolossbezwinger, Riesentöter oder Hordenbrecher.", "Colossus Slayer, Giant Killer or Horde Breaker."))],
                7: [F(("Verteidigungstaktik", "Defensive Tactics"), ("Der Horde entkommen, Mehrfachangriffs-Verteidigung oder Stählerner Wille.", "Escape the Horde, Multiattack Defense or Steel Will."))],
                11: [F(("Mehrfachangriff", "Multiattack"), ("Salve oder Wirbelangriff.", "Volley or Whirlwind Attack."))],
                15: [F(("Überlegene Jägerverteidigung", "Superior Hunter's Defense"), ("Entrinnen, Gegen den Strom oder Unheimliches Ausweichen.", "Evasion, Stand Against the Tide or Uncanny Dodge."))]}),
 dict(key="thief", name=("Dieb", "Thief"), parent="rogue", start=3,
      desc=("Einbrecher, Kletterer und Meister der Finger.", "Burglars, climbers and masters of the hand."),
      features={3: [F(("Flinke Hände", "Fast Hands"), ("Fingerfertigkeit, Diebeswerkzeug oder Gegenstand benutzen als Bonusaktion.", "Sleight of Hand, thieves' tools or Use an Object as a bonus action.")),
                    F(("Fassadenkletterer", "Second-Story Work"), ("Klettern ohne Zusatzkosten, weitere Sprünge.", "Climb at full speed and jump farther."))],
                9: [F(("Überragende Heimlichkeit", "Supreme Sneak"), ("Vorteil auf Heimlichkeit bei halber Geschwindigkeit.", "Advantage on Stealth when moving at half speed."))],
                13: [F(("Magische Gegenstände nutzen", "Use Magic Device"), ("Klassen-, Volks- und Stufenvoraussetzungen magischer Gegenstände ignorieren.", "Ignore class, race and level requirements of magic items."))],
                17: [F(("Diebesreflexe", "Thief's Reflexes"), ("In der ersten Runde zwei Züge.", "Take two turns in the first round of combat."))]}),
 dict(key="draconic", name=("Drakonische Blutlinie", "Draconic Bloodline"), parent="sorcerer", start=1,
      desc=("Die Magie stammt von einem Drachen unter deinen Vorfahren.", "Your magic comes from a dragon ancestor."),
      features={1: [F(("Drachenahn", "Dragon Ancestor"), ("Drachenart wählen; Drakonisch sprechen.", "Choose a dragon type; speak Draconic."), [{"type": "damage_type", "count": 1}]),
                    F(("Drakonische Widerstandskraft", "Draconic Resilience"), ("+1 TP pro Stufe; ohne Rüstung RK 13 + GES.", "+1 HP per level; AC 13 + DEX without armour."))],
                6: [F(("Elementare Affinität", "Elemental Affinity"), ("+CHA auf Schaden deiner Drachen-Schadensart; Resistenz für 1 Zauberpunkt.", "+CHA to damage of your dragon type; resistance for 1 sorcery point."))],
                14: [F(("Drachenschwingen", "Dragon Wings"), ("Bonusaktion: Flügel mit Fluggeschwindigkeit.", "Bonus action: sprout wings with a flying speed."))],
                18: [F(("Drakonische Präsenz", "Draconic Presence"), ("5 Zauberpunkte: Aura der Ehrfurcht oder Furcht.", "5 sorcery points: an aura of awe or fear."))]}),
 dict(key="fiend", name=("Der Unhold", "The Fiend"), parent="warlock", start=1,
      desc=("Ein Pakt mit einem Wesen der unteren Ebenen.", "A pact with a being of the lower planes."),
      features={1: [F(("Erweiterte Zauberliste", "Expanded Spell List"), ("Zusätzlich wählbar: u. a. Brennende Hände, Feuerball, Feuerwand.", "Additional options: e.g. burning hands, fireball, wall of fire.")),
                    F(("Segen des Dunklen", "Dark One's Blessing"), ("Bringst du einen Feind auf 0 TP: temporäre TP = CHA + Stufe.", "When you drop a foe to 0 HP: temporary HP = CHA + level."))],
                6: [F(("Glück des Dunklen", "Dark One's Own Luck"), ("+1W10 auf eine Probe oder einen Rettungswurf (einmal pro Rast).", "+1d10 to a check or save (once per rest)."))],
                10: [F(("Unholdische Widerstandskraft", "Fiendish Resilience"), ("Nach jeder Rast Resistenz gegen eine Schadensart.", "After each rest gain resistance to one damage type."))],
                14: [F(("Durch die Hölle schleudern", "Hurl Through Hell"), ("Nach einem Treffer: Ziel durch die Hölle, 10W10 psychischer Schaden.", "After a hit: the target is hurled through hell, 10d10 psychic damage."))]}),
 dict(key="evocation", name=("Hervorrufung", "School of Evocation"), aliases=["Schule der Hervorrufung"], parent="wizard", start=2,
      desc=("Magier, die Elementargewalten entfesseln.", "Wizards who unleash elemental power."),
      features={2: [F(("Hervorrufungs-Gelehrter", "Evocation Savant"), ("Hervorrufungszauber halb so teuer abzuschreiben.", "Copy evocation spells at half cost.")),
                    F(("Zauber formen", "Sculpt Spells"), ("Verbündete aus Flächenzaubern aussparen.", "Exclude allies from your area spells."))],
                6: [F(("Wirksamer Zaubertrick", "Potent Cantrip"), ("Bestandene Rettungswürfe gegen deine Zaubertricks: halber Schaden.", "Successful saves against your cantrips still take half damage."))],
                10: [F(("Verstärkte Hervorrufung", "Empowered Evocation"), ("+INT auf den Schaden von Hervorrufungszaubern.", "+INT to the damage of evocation spells."))],
                14: [F(("Überladen", "Overchannel"), ("Zauber bis 5. Grad mit maximalem Schaden (danach nekrotischer Schaden an dir).", "Spells up to 5th level deal maximum damage (with necrotic backlash)."))]}),
]

BACKGROUNDS = [
 dict(key="acolyte", name=("Akolyth", "Acolyte"), skills=skills("insight", "religion"), languages=("Zwei Sprachen deiner Wahl", "Two languages of your choice"),
      tools=("", ""), equipment=("Heiliges Symbol, Gebetbuch, 5 Räucherstäbchen, Gewänder, Alltagskleidung, 15 GM", "Holy symbol, prayer book, 5 sticks of incense, vestments, common clothes, 15 gp"),
      feature=("Zuflucht der Gläubigen: Tempel deines Glaubens gewähren dir und deinen Gefährten Hilfe.", "Shelter of the Faithful: temples of your faith offer you and your companions aid."),
      desc=("Du hast dein Leben dem Dienst in einem Tempel gewidmet.", "You have spent your life in service to a temple.")),
]
FEATS = [
 dict(key="grappler", name=("Ringer", "Grappler"), prereq=("STR 13", "STR 13"),
      desc=("Geübt im Nahkampf auf engstem Raum.", "Skilled at close-quarters grappling."),
      benefits=("Vorteil auf Angriffe gegen eine gepackte Kreatur. Als Aktion eine gepackte Kreatur festsetzen.", "Advantage on attacks against a creature you grapple. Use an action to pin a grappled creature.")),
]
CONDITIONS = [
 (("Blind", "Blinded"), ("Sieht nichts; Angriffe gegen dich mit Vorteil, eigene mit Nachteil.", "Can't see; attacks against you have advantage, yours have disadvantage.")),
 (("Bezaubert", "Charmed"), ("Kann den Bezauberer nicht angreifen; er hat Vorteil bei sozialen Proben.", "Can't attack the charmer; it has advantage on social checks.")),
 (("Taub", "Deafened"), ("Hört nichts.", "Can't hear.")),
 (("Erschöpft", "Exhaustion"), ("Sechs Stufen mit wachsenden Nachteilen; Stufe 6 bedeutet den Tod.", "Six levels with growing penalties; level 6 means death.")),
 (("Verängstigt", "Frightened"), ("Nachteil, solange die Quelle sichtbar ist; kann sich ihr nicht nähern.", "Disadvantage while the source is visible; can't move closer to it.")),
 (("Gepackt", "Grappled"), ("Geschwindigkeit 0.", "Speed becomes 0.")),
 (("Kampfunfähig", "Incapacitated"), ("Keine Aktionen und Reaktionen.", "Can't take actions or reactions."), ["Handlungsunfähig"]),
 (("Unsichtbar", "Invisible"), ("Nicht ohne Hilfe zu sehen; eigene Angriffe mit Vorteil, gegen dich mit Nachteil.", "Can't be seen without help; your attacks have advantage, attacks against you disadvantage.")),
 (("Gelähmt", "Paralyzed"), ("Kampfunfähig, keine Bewegung; Nahkampftreffer sind kritisch.", "Incapacitated and can't move; melee hits are critical.")),
 (("Versteinert", "Petrified"), ("In Stein verwandelt; Resistenz gegen allen Schaden.", "Turned to stone; resistance to all damage.")),
 (("Vergiftet", "Poisoned"), ("Nachteil auf Angriffe und Attributsproben.", "Disadvantage on attacks and ability checks.")),
 (("Liegend", "Prone"), ("Kriechen; Nahkampf gegen dich mit Vorteil, Fernkampf mit Nachteil.", "Crawl only; melee attacks against you have advantage, ranged disadvantage.")),
 (("Festgesetzt", "Restrained"), ("Geschwindigkeit 0; Angriffe gegen dich mit Vorteil, eigene mit Nachteil.", "Speed 0; attacks against you have advantage, yours disadvantage."), ["Zurückgehalten"]),
 (("Betäubt", "Stunned"), ("Kampfunfähig; Angriffe gegen dich mit Vorteil.", "Incapacitated; attacks against you have advantage.")),
 (("Bewusstlos", "Unconscious"), ("Kampfunfähig, liegend; Nahkampftreffer sind kritisch.", "Incapacitated and prone; melee hits are critical.")),
]
LANGUAGES = [
 (("Gemeinsprache", "Common"), "Standard", ("Gemeinsprache", "Common"), ("Menschen", "Humans")),
 (("Zwergisch", "Dwarvish"), "Standard", ("Zwergisch", "Dwarvish"), ("Zwerge", "Dwarves")),
 (("Elfisch", "Elvish"), "Standard", ("Elfisch", "Elvish"), ("Elfen", "Elves")),
 (("Riesisch", "Giant"), "Standard", ("Zwergisch", "Dwarvish"), ("Oger, Riesen", "Ogres, giants")),
 (("Gnomisch", "Gnomish"), "Standard", ("Zwergisch", "Dwarvish"), ("Gnome", "Gnomes")),
 (("Goblinisch", "Goblin"), "Standard", ("Zwergisch", "Dwarvish"), ("Goblinoide", "Goblinoids")),
 (("Halblingisch", "Halfling"), "Standard", ("Gemeinsprache", "Common"), ("Halblinge", "Halflings")),
 (("Orkisch", "Orc"), "Standard", ("Zwergisch", "Dwarvish"), ("Orks", "Orcs")),
 (("Abyssisch", "Abyssal"), "Exotisch", ("Infernalisch", "Infernal"), ("Dämonen", "Demons")),
 (("Celestisch", "Celestial"), "Exotisch", ("Celestisch", "Celestial"), ("Celestische Wesen", "Celestials")),
 (("Drakonisch", "Draconic"), "Exotisch", ("Drakonisch", "Draconic"), ("Drachen, Drachenblütige", "Dragons, dragonborn")),
 (("Tiefensprache", "Deep Speech"), "Exotisch", ("—", "—"), ("Wesen der Tiefe", "Aberrations")),
 (("Infernalisch", "Infernal"), "Exotisch", ("Infernalisch", "Infernal"), ("Teufel", "Devils")),
 (("Urtümlich", "Primordial"), "Exotisch", ("Zwergisch", "Dwarvish"), ("Elementare", "Elementals")),
 (("Sylvanisch", "Sylvan"), "Exotisch", ("Elfisch", "Elvish"), ("Feenwesen", "Fey creatures")),
 (("Gemeinsprache der Unterreiche", "Undercommon"), "Exotisch", ("Elfisch", "Elvish"), ("Händler der Unterreiche", "Underworld traders")),
]
